// lang-fr.js — French translations
registerLanguage('fr', {
  // Header
  'header.title': 'Créateur de Cartes <b>Jeux de Plateau</b> Historiques',

  // Year formatting
  'year.bc': 'av. J.-C.',
  'year.ad': 'ap. J.-C.',

  // Eras
  'era.prehistory': 'Préhistoire',
  'era.antiquity': 'Antiquité',
  'era.firstmill': 'Premier Millénaire',
  'era.medieval': 'Moyen Âge',
  'era.earlymodern': 'Époque Moderne',
  'era.nineteenth': 'XIXe Siècle',
  'era.twentieth': 'XXe Siècle',
  'era.twentyfirst': 'XXIe Siècle',

  // Panels
  'panel.year': '📅 Année Historique',
  'panel.style': '🎨 Style de Carte & Frontières',
  'panel.colors': '🏳️ Couleurs des Nations',
  'panel.tools': '🛠️ Outils',
  'panel.annotations': '📋 Annotations',
  'panel.import': '📂 Importer GeoJSON',
  'panel.export': '💾 Exporter',

  // Basemaps
  'basemap.label': 'Fond de Carte',
  'basemap.physical': 'Physique',
  'basemap.relief': 'Relief Ombré',
  'basemap.natgeo': 'National Geographic',
  'basemap.topo': 'Topographique',
  'basemap.satellite': 'Satellite',
  'basemap.dark': 'Sombre',
  'basemap.watercolor': 'Aquarelle',
  'basemap.none': 'Aucun',

  // Border styles
  'border.style.label': 'Style des Frontières',
  'border.solid': 'Continu',
  'border.dashed': 'Tirets',
  'border.dotted': 'Pointillé',
  'border.dashdot': 'Tiret-Point',
  'border.longdash': 'Tirets Longs',
  'border.double': 'Double',
  'border.sketch': 'Croquis',
  'border.railroad': 'Chemin de Fer',
  'border.desc.solid': 'Ligne continue nette',
  'border.desc.dashed': 'Tirets classiques',
  'border.desc.dotted': 'Motif pointillé',
  'border.desc.dashdot': 'Motif tiret-point',
  'border.desc.longdash': 'Tirets longs',
  'border.desc.double': 'Ligne double',
  'border.desc.sketch': 'Style dessiné à la main',
  'border.desc.railroad': 'Style chemin de fer',
  'border.width': 'Épaisseur des Frontières',
  'border.px': 'px',
  'border.color': 'Couleur des Frontières',
  'fill.opacity': 'Opacité du Remplissage',

  // Colors panel
  'colors.selected': 'Nations Sélectionnées',
  'colors.hint': 'Clic = sélection · Ctrl+Clic = multiple · Shift+Clic = plage',
  'colors.empty': 'Cliquez sur les nations sur la carte',
  'colors.all': '✅ Toutes',
  'colors.invert': '🔄 Inverser',
  'colors.none': '✖ Aucune',
  'colors.apply.label': 'Appliquer couleur :',
  'colors.custom.label': 'Personnalisée :',
  'colors.apply': 'Appliquer',
  'colors.reset': '↺ Réinitialiser',

  // Tools
  'tool.navigate': '🖱️ Naviguer',
  'tool.text': '✏️ Texte',
  'tool.flag': '🏴 Drapeau',
  'tool.draw': '🖊️ Dessiner',

  // Text tool
  'text.label': 'Texte',
  'text.placeholder': 'Entrez le texte...',
  'text.size': 'Taille',
  'text.color': 'Couleur',
  'text.bold': 'Gras',
  'text.outline': 'Contour',
  'text.rotation': 'Rotation',

  // Flag tool
  'flag.shape': 'Forme du Drapeau',
  'flag.circle': '🔵 Rond',
  'flag.rect': '🟦 Rectangle',
  'flag.search': 'Rechercher',
  'flag.search.placeholder': 'Rechercher pays...',
  'flag.size': 'Taille',
  'flag.upload.title': 'Charger drapeau personnalisé',
  'flag.upload.desc': 'PNG, SVG, JPG',
  'flag.name.placeholder': 'Nom du drapeau...',
  'flag.add': '➕ Ajouter',
  'flag.builtin': 'Drapeaux Intégrés',
  'flag.custom.section': 'Drapeaux Personnalisés',
  'flag.select.hint': '👆 Sélectionnez, puis cliquez sur la carte',
  'flag.selected': 'Sélectionné : {name}',

  // Draw tool
  'draw.world.mode': 'Mode Monde',
  'draw.world.existing': '🌍 Existant',
  'draw.world.empty': '📄 Vide',
  'draw.border.type': 'Type de Frontière',
  'draw.type.land': '🏔️ Terrestre',
  'draw.type.sea': '🌊 Maritime',
  'draw.region.name': 'Nom de la Région',
  'draw.region.placeholder': 'Nouvelle Région',
  'draw.region.color': 'Couleur de la Région',
  'draw.start': '✏️ Commencer le Dessin',
  'draw.undo': '↩️ Annuler',
  'draw.cancel': '✕ Annuler',
  'draw.finish': '✓ Terminer',
  'draw.info.land.desc': 'Découpé sur le littoral, reste sur terre uniquement.',
  'draw.info.sea.desc': 'Découpé sur le littoral, reste en mer uniquement.',
  'draw.info.overlap.desc': 'Découpage automatique contre les régions existantes.',
  'draw.regions.title': 'Régions Personnalisées',
  'draw.regions.empty': 'Aucune région créée.',
  'draw.regions.clear': '🗑️ Supprimer Tout',

  // Draw status messages
  'draw.loading.coastline': 'Chargement des lignes côtières...',
  'draw.mode.empty': 'Mode monde vide — dessinez vos frontières',
  'draw.mode.existing': 'Mode frontières existantes — frontières historiques chargées',
  'draw.mode.land.hint': 'Frontière terrestre : sera découpée sur le littoral',
  'draw.mode.sea.hint': 'Frontière maritime : ne peut pas traverser la terre',
  'draw.started': 'Cliquez pour ajouter des points, double-clic ou premier point pour terminer',
  'draw.points': 'Points : {count}',
  'draw.point.removed': 'Point supprimé',
  'draw.cancelled': 'Dessin annulé',
  'draw.need.3.points': 'Minimum 3 points requis',
  'draw.fully.outside': 'Région entièrement hors zone valide (terre/mer)',
  'draw.snapped.region': 'Accroché à la région',
  'draw.snapped.coast.land': 'Accroché à la côte (mode terre)',
  'draw.snapped.coast.sea': 'Accroché à la côte (mode mer)',
  'draw.cannot.cross.land': '⛔ La frontière maritime ne peut pas traverser la terre !',
  'draw.region.created': '"{name}" créée ({count} points)',
  'draw.clipped.to.land': '· découpée sur terre',
  'draw.clipped.to.sea': '· découpée sur mer',
  'draw.clipped.regions': '· découpée contre régions',
  'draw.region.removed': 'Région supprimée',
  'draw.regions.cleared': 'Toutes les régions supprimées',

  // Edit mode
  'edit.mode': 'Mode Édition',
  'edit.editing': 'Édition',
  'edit.vertices': 'sommets',
  'edit.drag': 'Glisser pour déplacer',
  'edit.dblclick': 'Double-clic pour supprimer',
  'edit.midpoint': 'Clic sur point médian pour ajouter',
  'edit.vertex.added': 'Sommet ajouté',
  'edit.vertex.removed': 'Sommet supprimé',
  'edit.min.vertices': 'Impossible de supprimer : minimum 3 sommets',
  'edit.clipped': 'Région découpée dans la zone valide',
  'edit.done': 'Édition terminée',

  // Annotations
  'ann.empty': 'Aucune annotation.',
  'ann.removeall': '🗑️ Supprimer Tout',

  // Import
  'import.hint': 'Charger des frontières GeoJSON personnalisées.',

  // Export
  'export.format': 'Format',
  'export.png': 'Image PNG',
  'export.pdf': 'Document PDF',
  'export.svg': 'Vecteur SVG',
  'export.width': 'Largeur',
  'export.height': 'Hauteur',
  'export.page': 'Taille de Page',
  'export.custom.mm': 'Personnalisé (mm)',
  'export.orientation': 'Orientation',
  'export.landscape': 'Paysage',
  'export.portrait': 'Portrait',
  'export.dpi': 'DPI',
  'export.view.info': '📐 <b>Exporte la zone visible.</b> Déplacez et zoomez pour cadrer votre carte.',
  'export.world': '🌍 Monde',
  'export.fit': '📐 Ajuster',
  'export.button': '💾 Exporter la Vue Actuelle',
  'export.modal.title': '⏳ Exportation',
  'export.preparing': 'Préparation de l\'exportation...',
  'export.rendering.tiles': 'Rendu des tuiles...',
  'export.rendering.poly': 'Rendu des frontières...',
  'export.generating': 'Génération du fichier...',
  'export.done': 'Terminé !',

  // Banners
  'banner.text': '✏️ Cliquez sur la carte pour placer le texte',
  'banner.flag.select': '🏴 Sélectionnez d\'abord un drapeau',
  'banner.flag.place': '🏴 Cliquez pour placer {name}',
  'banner.custom.place': '📁 Cliquez pour placer {name}',
  'banner.draw': '🖊️ Cliquez pour dessiner, ou sélectionnez une région à modifier',
  'banner.cancel': '✕',

  // Status messages
  'status.ready': 'Prêt',
  'status.loading': 'Chargement {year}...',
  'status.loaded': '{year} : {count} territoires ✓',
  'status.cached': '{year} : {count} territoires (cache) ✓',
  'status.error': 'Erreur chargement {year} : {msg}',
  'status.nation.selected': '{count} nation sélectionnée',
  'status.nations.selected': '{count} nations sélectionnées',
  'status.all.selected': 'Les {count} nations sélectionnées',
  'status.inverted': 'Sélection inversée ({count} sélectionnées)',
  'status.deselected': 'Sélection annulée',
  'status.select.nation.first': 'Sélectionnez d\'abord des nations',
  'status.color.applied': 'Couleur {color} appliquée à {count} nation(s)',
  'status.colors.reset': 'Toutes les couleurs réinitialisées',
  'status.text.placed': 'Texte "{text}" placé',
  'status.flag.select.first': 'Sélectionnez d\'abord un drapeau',
  'status.flag.placed': '{name} placé',
  'status.custom.added': 'Drapeau personnalisé "{name}" ajouté',
  'status.custom.removed': 'Drapeau personnalisé supprimé',
  'status.format.unsupported': 'Format de fichier non supporté',
  'status.ann.removed': 'Annotation supprimée',
  'status.ann.cleared': 'Toutes les annotations supprimées',
  'status.imported': '{count} éléments importés',

  // Loading
  'loading.text': 'Chargement...',

  // Countries
  'country.us': 'États-Unis',
  'country.gb': 'Royaume-Uni',
  'country.fr': 'France',
  'country.de': 'Allemagne',
  'country.it': 'Italie',
  'country.jp': 'Japon',
  'country.ru': 'Russie',
  'country.cn': 'Chine',
  'country.ca': 'Canada',
  'country.au': 'Australie',
  'country.br': 'Brésil',
  'country.in': 'Inde',
  'country.es': 'Espagne',
  'country.pt': 'Portugal',
  'country.nl': 'Pays-Bas',
  'country.be': 'Belgique',
  'country.pl': 'Pologne',
  'country.tr': 'Turquie',
  'country.mx': 'Mexique',
  'country.ar': 'Argentine',
  'country.se': 'Suède',
  'country.no': 'Norvège',
  'country.fi': 'Finlande',
  'country.dk': 'Danemark',
  'country.gr': 'Grèce',
  'country.at': 'Autriche',
  'country.hu': 'Hongrie',
  'country.ro': 'Roumanie',
  'country.bg': 'Bulgarie',
  'country.rs': 'Serbie',
  'country.hr': 'Croatie',
  'country.ch': 'Suisse',
  'country.ie': 'Irlande',
  'country.za': 'Afrique du Sud',
  'country.eg': 'Égypte',
  'country.sa': 'Arabie Saoudite',
  'country.ir': 'Iran',
  'country.iq': 'Irak',
  'country.th': 'Thaïlande',
  'country.kr': 'Corée du Sud',
  'country.nz': 'Nouvelle-Zélande',
  'country.ua': 'Ukraine',
  'country.cu': 'Cuba',
  'country.et': 'Éthiopie',
  'country.ng': 'Nigeria',
  'country.pk': 'Pakistan',
  'country.af': 'Afghanistan',
  'country.cl': 'Chili',
  'country.co': 'Colombie',
  'country.pe': 'Pérou',
  'country.ve': 'Venezuela',
  'country.dz': 'Algérie',
  'country.ma': 'Maroc',
  'country.ly': 'Libye',
  'country.sd': 'Soudan',
  'country.tn': 'Tunisie',
  'country.sy': 'Syrie',
  'country.jo': 'Jordanie',
  'country.lb': 'Liban',
  'country.il': 'Israël',
  'country.mm': 'Myanmar',
  'country.vn': 'Vietnam',
  'country.ph': 'Philippines',
  'country.id': 'Indonésie',
  'country.my': 'Malaisie',
  'country.bd': 'Bangladesh',
  'country.lk': 'Sri Lanka',
  'country.ke': 'Kenya'
});