// lang-zh.js — Chinese (Simplified) translations
registerLanguage('zh', {
  // Header
  'header.title': '历史<b>桌游</b>地图制作器',

  // Year formatting
  'year.bc': '公元前',
  'year.ad': '公元',

  // Eras
  'era.prehistory': '史前时代',
  'era.antiquity': '古代',
  'era.firstmill': '第一千年',
  'era.medieval': '中世纪',
  'era.earlymodern': '近代早期',
  'era.nineteenth': '十九世纪',
  'era.twentieth': '二十世纪',
  'era.twentyfirst': '二十一世纪',

  // Panels
  'panel.year': '📅 历史年份',
  'panel.style': '🎨 地图样式与边界',
  'panel.colors': '🏳️ 国家颜色',
  'panel.tools': '🛠️ 工具',
  'panel.annotations': '📋 注释',
  'panel.import': '📂 导入GeoJSON',
  'panel.export': '💾 导出',

  // Basemaps
  'basemap.label': '底图',
  'basemap.physical': '自然地图',
  'basemap.relief': '地形阴影',
  'basemap.natgeo': '国家地理',
  'basemap.topo': '地形图',
  'basemap.satellite': '卫星',
  'basemap.dark': '暗色',
  'basemap.watercolor': '水彩',
  'basemap.none': '无',

  // Border styles
  'border.style.label': '边界样式',
  'border.solid': '实线',
  'border.dashed': '虚线',
  'border.dotted': '点线',
  'border.dashdot': '点划线',
  'border.longdash': '长虚线',
  'border.double': '双线',
  'border.sketch': '素描',
  'border.railroad': '铁路线',
  'border.desc.solid': '清晰实线',
  'border.desc.dashed': '经典虚线',
  'border.desc.dotted': '点状图案',
  'border.desc.dashdot': '点划图案',
  'border.desc.longdash': '长虚线',
  'border.desc.double': '双线',
  'border.desc.sketch': '手绘风格',
  'border.desc.railroad': '铁路风格',
  'border.width': '边界宽度',
  'border.px': '像素',
  'border.color': '边界颜色',
  'fill.opacity': '填充不透明度',

  // Colors panel
  'colors.selected': '已选择国家',
  'colors.hint': '点击=选择 · Ctrl+点击=多选 · Shift+点击=范围选择',
  'colors.empty': '点击地图上的国家',
  'colors.all': '✅ 全选',
  'colors.invert': '🔄 反选',
  'colors.none': '✖ 清除',
  'colors.apply.label': '应用颜色：',
  'colors.custom.label': '自定义：',
  'colors.apply': '应用',
  'colors.reset': '↺ 重置',

  // Tools
  'tool.navigate': '🖱️ 导航',
  'tool.text': '✏️ 文字',
  'tool.flag': '🏴 旗帜',
  'tool.draw': '🖊️ 绘制',

  // Text tool
  'text.label': '文字',
  'text.placeholder': '输入文字...',
  'text.size': '大小',
  'text.color': '颜色',
  'text.bold': '粗体',
  'text.outline': '轮廓',
  'text.rotation': '旋转',

  // Flag tool
  'flag.shape': '旗帜形状',
  'flag.circle': '🔵 圆形',
  'flag.rect': '🟦 矩形',
  'flag.search': '搜索',
  'flag.search.placeholder': '搜索国家...',
  'flag.size': '大小',
  'flag.upload.title': '上传自定义旗帜',
  'flag.upload.desc': 'PNG, SVG, JPG',
  'flag.name.placeholder': '旗帜名称...',
  'flag.add': '➕ 添加',
  'flag.builtin': '内置旗帜',
  'flag.custom.section': '自定义旗帜',
  'flag.select.hint': '👆 选择后点击地图',
  'flag.selected': '已选择：{name}',

  // Draw tool
  'draw.world.mode': '世界模式',
  'draw.world.existing': '🌍 现有',
  'draw.world.empty': '📄 空白',
  'draw.border.type': '边界类型',
  'draw.type.land': '🏔️ 陆地',
  'draw.type.sea': '🌊 海洋',
  'draw.region.name': '区域名称',
  'draw.region.placeholder': '新区域',
  'draw.region.color': '区域颜色',
  'draw.start': '✏️ 开始绘制',
  'draw.undo': '↩️ 撤销',
  'draw.cancel': '✕ 取消',
  'draw.finish': '✓ 完成',
  'draw.info.land.desc': '沿海岸线裁剪，仅保留陆地。',
  'draw.info.sea.desc': '沿海岸线裁剪，仅保留海洋。',
  'draw.info.overlap.desc': '自动裁剪以避免与现有区域重叠。',
  'draw.regions.title': '自定义区域',
  'draw.regions.empty': '未创建区域。',
  'draw.regions.clear': '🗑️ 全部删除',

  // Draw status messages
  'draw.loading.coastline': '加载海岸线数据...',
  'draw.mode.empty': '空白世界模式 — 绘制您自己的边界',
  'draw.mode.existing': '现有边界模式 — 已加载历史边界',
  'draw.mode.land.hint': '陆地边界：将沿海岸线裁剪',
  'draw.mode.sea.hint': '海洋边界：不能穿越陆地',
  'draw.started': '点击添加点，双击或点击第一个点完成',
  'draw.points': '点数：{count}',
  'draw.point.removed': '点已删除',
  'draw.cancelled': '绘制已取消',
  'draw.need.3.points': '至少需要3个点',
  'draw.fully.outside': '区域完全在有效范围外（陆地/海洋）',
  'draw.snapped.region': '已吸附到区域',
  'draw.snapped.coast.land': '已吸附到海岸（陆地模式）',
  'draw.snapped.coast.sea': '已吸附到海岸（海洋模式）',
  'draw.cannot.cross.land': '⛔ 海洋边界不能穿越陆地！',
  'draw.region.created': '"{name}" 已创建（{count} 个点）',
  'draw.clipped.to.land': '· 已裁剪到陆地',
  'draw.clipped.to.sea': '· 已裁剪到海洋',
  'draw.clipped.regions': '· 已裁剪以避免重叠',
  'draw.region.removed': '区域已删除',
  'draw.regions.cleared': '所有区域已删除',

  // Edit mode
  'edit.mode': '编辑模式',
  'edit.editing': '编辑中',
  'edit.vertices': '顶点',
  'edit.drag': '拖动移动',
  'edit.dblclick': '双击删除',
  'edit.midpoint': '点击中点添加',
  'edit.vertex.added': '顶点已添加',
  'edit.vertex.removed': '顶点已删除',
  'edit.min.vertices': '无法删除：最少需要3个顶点',
  'edit.clipped': '区域已裁剪到有效范围',
  'edit.done': '编辑完成',

  // Annotations
  'ann.empty': '无注释。',
  'ann.removeall': '🗑️ 全部删除',

  // Import
  'import.hint': '加载自定义GeoJSON边界。',

  // Export
  'export.format': '格式',
  'export.png': 'PNG图片',
  'export.pdf': 'PDF文档',
  'export.svg': 'SVG矢量',
  'export.width': '宽度',
  'export.height': '高度',
  'export.page': '页面大小',
  'export.custom.mm': '自定义（毫米）',
  'export.orientation': '方向',
  'export.landscape': '横向',
  'export.portrait': '纵向',
  'export.dpi': 'DPI',
  'export.view.info': '📐 <b>导出可见区域。</b>平移和缩放以调整地图。',
  'export.world': '🌍 世界',
  'export.fit': '📐 适应',
  'export.button': '💾 导出当前视图',
  'export.modal.title': '⏳ 导出中',
  'export.preparing': '准备导出...',
  'export.rendering.tiles': '渲染地图瓦片...',
  'export.rendering.poly': '渲染边界...',
  'export.generating': '生成文件...',
  'export.done': '完成！',

  // Banners
  'banner.text': '✏️ 点击地图放置文字',
  'banner.flag.select': '🏴 请先选择一面旗帜',
  'banner.flag.place': '🏴 点击放置 {name}',
  'banner.custom.place': '📁 点击放置 {name}',
  'banner.draw': '🖊️ 点击开始绘制，或选择区域进行编辑',
  'banner.cancel': '✕',

  // Status messages
  'status.ready': '就绪',
  'status.loading': '加载 {year}...',
  'status.loaded': '{year}：{count} 个领土 ✓',
  'status.cached': '{year}：{count} 个领土（缓存）✓',
  'status.error': '加载 {year} 出错：{msg}',
  'status.nation.selected': '已选择 {count} 个国家',
  'status.nations.selected': '已选择 {count} 个国家',
  'status.all.selected': '已选择全部 {count} 个国家',
  'status.inverted': '选择已反转（{count} 个已选）',
  'status.deselected': '选择已清除',
  'status.select.nation.first': '请先选择国家',
  'status.color.applied': '颜色 {color} 已应用于 {count} 个国家',
  'status.colors.reset': '所有颜色已重置',
  'status.text.placed': '文字 "{text}" 已放置',
  'status.flag.select.first': '请先选择一面旗帜',
  'status.flag.placed': '{name} 已放置',
  'status.custom.added': '自定义旗帜 "{name}" 已添加',
  'status.custom.removed': '自定义旗帜已删除',
  'status.format.unsupported': '不支持的文件格式',
  'status.ann.removed': '注释已删除',
  'status.ann.cleared': '所有注释已删除',
  'status.imported': '已导入 {count} 个要素',

  // Loading
  'loading.text': '加载中...',

  // Countries
  'country.us': '美国',
  'country.gb': '英国',
  'country.fr': '法国',
  'country.de': '德国',
  'country.it': '意大利',
  'country.jp': '日本',
  'country.ru': '俄罗斯',
  'country.cn': '中国',
  'country.ca': '加拿大',
  'country.au': '澳大利亚',
  'country.br': '巴西',
  'country.in': '印度',
  'country.es': '西班牙',
  'country.pt': '葡萄牙',
  'country.nl': '荷兰',
  'country.be': '比利时',
  'country.pl': '波兰',
  'country.tr': '土耳其',
  'country.mx': '墨西哥',
  'country.ar': '阿根廷',
  'country.se': '瑞典',
  'country.no': '挪威',
  'country.fi': '芬兰',
  'country.dk': '丹麦',
  'country.gr': '希腊',
  'country.at': '奥地利',
  'country.hu': '匈牙利',
  'country.ro': '罗马尼亚',
  'country.bg': '保加利亚',
  'country.rs': '塞尔维亚',
  'country.hr': '克罗地亚',
  'country.ch': '瑞士',
  'country.ie': '爱尔兰',
  'country.za': '南非',
  'country.eg': '埃及',
  'country.sa': '沙特阿拉伯',
  'country.ir': '伊朗',
  'country.iq': '伊拉克',
  'country.th': '泰国',
  'country.kr': '韩国',
  'country.nz': '新西兰',
  'country.ua': '乌克兰',
  'country.cu': '古巴',
  'country.et': '埃塞俄比亚',
  'country.ng': '尼日利亚',
  'country.pk': '巴基斯坦',
  'country.af': '阿富汗',
  'country.cl': '智利',
  'country.co': '哥伦比亚',
  'country.pe': '秘鲁',
  'country.ve': '委内瑞拉',
  'country.dz': '阿尔及利亚',
  'country.ma': '摩洛哥',
  'country.ly': '利比亚',
  'country.sd': '苏丹',
  'country.tn': '突尼斯',
  'country.sy': '叙利亚',
  'country.jo': '约旦',
  'country.lb': '黎巴嫩',
  'country.il': '以色列',
  'country.mm': '缅甸',
  'country.vn': '越南',
  'country.ph': '菲律宾',
  'country.id': '印度尼西亚',
  'country.my': '马来西亚',
  'country.bd': '孟加拉国',
  'country.lk': '斯里兰卡',
  'country.ke': '肯尼亚'
});