// lang-ar.js — Arabic translations (RTL)
registerLanguage('ar', {
  // Header
  'header.title': 'صانع خرائط <b>ألعاب الطاولة</b> التاريخية',

  // Year formatting
  'year.bc': 'ق.م',
  'year.ad': 'م',

  // Eras
  'era.prehistory': 'ما قبل التاريخ',
  'era.antiquity': 'العصور القديمة',
  'era.firstmill': 'الألفية الأولى',
  'era.medieval': 'العصور الوسطى',
  'era.earlymodern': 'العصر الحديث المبكر',
  'era.nineteenth': 'القرن التاسع عشر',
  'era.twentieth': 'القرن العشرون',
  'era.twentyfirst': 'القرن الحادي والعشرون',

  // Panels
  'panel.year': '📅 السنة التاريخية',
  'panel.style': '🎨 نمط الخريطة والحدود',
  'panel.colors': '🏳️ ألوان الدول',
  'panel.tools': '🛠️ الأدوات',
  'panel.annotations': '📋 التعليقات',
  'panel.import': '📂 استيراد GeoJSON',
  'panel.export': '💾 تصدير',

  // Basemaps
  'basemap.label': 'الخريطة الأساسية',
  'basemap.physical': 'طبيعية',
  'basemap.relief': 'تضاريس مظللة',
  'basemap.natgeo': 'ناشيونال جيوغرافيك',
  'basemap.topo': 'طبوغرافية',
  'basemap.satellite': 'قمر صناعي',
  'basemap.dark': 'داكنة',
  'basemap.watercolor': 'ألوان مائية',
  'basemap.none': 'بدون',

  // Border styles
  'border.style.label': 'نمط الحدود',
  'border.solid': 'متصل',
  'border.dashed': 'متقطع',
  'border.dotted': 'منقط',
  'border.dashdot': 'شرطة-نقطة',
  'border.longdash': 'شرطة طويلة',
  'border.double': 'مزدوج',
  'border.sketch': 'رسم يدوي',
  'border.railroad': 'سكة حديد',
  'border.desc.solid': 'خط متصل نظيف',
  'border.desc.dashed': 'متقطع كلاسيكي',
  'border.desc.dotted': 'نمط منقط',
  'border.desc.dashdot': 'نمط شرطة-نقطة',
  'border.desc.longdash': 'شرطات طويلة',
  'border.desc.double': 'خط مزدوج',
  'border.desc.sketch': 'نمط مرسوم يدوياً',
  'border.desc.railroad': 'نمط سكة حديد',
  'border.width': 'عرض الحدود',
  'border.px': 'بكسل',
  'border.color': 'لون الحدود',
  'fill.opacity': 'شفافية التعبئة',

  // Colors panel
  'colors.selected': 'الدول المحددة',
  'colors.hint': 'نقر = تحديد · Ctrl+نقر = متعدد · Shift+نقر = نطاق',
  'colors.empty': 'انقر على الدول في الخريطة',
  'colors.all': '✅ الكل',
  'colors.invert': '🔄 عكس',
  'colors.none': '✖ لا شيء',
  'colors.apply.label': 'تطبيق اللون:',
  'colors.custom.label': 'مخصص:',
  'colors.apply': 'تطبيق',
  'colors.reset': '↺ إعادة',

  // Tools
  'tool.navigate': '🖱️ تصفح',
  'tool.text': '✏️ نص',
  'tool.flag': '🏴 علم',
  'tool.draw': '🖊️ رسم',

  // Text tool
  'text.label': 'النص',
  'text.placeholder': 'أدخل النص...',
  'text.size': 'الحجم',
  'text.color': 'اللون',
  'text.bold': 'عريض',
  'text.outline': 'حدود',
  'text.rotation': 'الدوران',

  // Flag tool
  'flag.shape': 'شكل العلم',
  'flag.circle': '🔵 دائري',
  'flag.rect': '🟦 مستطيل',
  'flag.search': 'بحث',
  'flag.search.placeholder': 'ابحث عن دولة...',
  'flag.size': 'الحجم',
  'flag.upload.title': 'رفع علم مخصص',
  'flag.upload.desc': 'PNG, SVG, JPG',
  'flag.name.placeholder': 'اسم العلم...',
  'flag.add': '➕ إضافة',
  'flag.builtin': 'أعلام مدمجة',
  'flag.custom.section': 'أعلام مخصصة',
  'flag.select.hint': '👆 حدد ثم انقر على الخريطة',
  'flag.selected': 'محدد: {name}',

  // Draw tool
  'draw.world.mode': 'وضع العالم',
  'draw.world.existing': '🌍 موجود',
  'draw.world.empty': '📄 فارغ',
  'draw.border.type': 'نوع الحدود',
  'draw.type.land': '🏔️ بري',
  'draw.type.sea': '🌊 بحري',
  'draw.region.name': 'اسم المنطقة',
  'draw.region.placeholder': 'منطقة جديدة',
  'draw.region.color': 'لون المنطقة',
  'draw.start': '✏️ بدء الرسم',
  'draw.undo': '↩️ تراجع',
  'draw.cancel': '✕ إلغاء',
  'draw.finish': '✓ إنهاء',
  'draw.info.land.desc': 'يُقص على خط الساحل، يبقى على اليابسة فقط.',
  'draw.info.sea.desc': 'يُقص على خط الساحل، يبقى في البحر فقط.',
  'draw.info.overlap.desc': 'قص تلقائي ضد المناطق الموجودة.',
  'draw.regions.title': 'مناطق مخصصة',
  'draw.regions.empty': 'لا توجد مناطق.',
  'draw.regions.clear': '🗑️ حذف الكل',

  // Draw status messages
  'draw.loading.coastline': 'جاري تحميل خطوط الساحل...',
  'draw.mode.empty': 'وضع العالم الفارغ — ارسم حدودك',
  'draw.mode.existing': 'وضع الحدود الموجودة — تم تحميل الحدود التاريخية',
  'draw.mode.land.hint': 'حدود برية: ستُقص على خط الساحل',
  'draw.mode.sea.hint': 'حدود بحرية: لا يمكن عبور اليابسة',
  'draw.started': 'انقر لإضافة نقاط، نقر مزدوج أو النقطة الأولى للإنهاء',
  'draw.points': 'النقاط: {count}',
  'draw.point.removed': 'تم حذف النقطة',
  'draw.cancelled': 'تم إلغاء الرسم',
  'draw.need.3.points': 'يلزم 3 نقاط على الأقل',
  'draw.fully.outside': 'المنطقة خارج النطاق الصالح بالكامل (بر/بحر)',
  'draw.snapped.region': 'تم الالتصاق بالمنطقة',
  'draw.snapped.coast.land': 'تم الالتصاق بالساحل (وضع بري)',
  'draw.snapped.coast.sea': 'تم الالتصاق بالساحل (وضع بحري)',
  'draw.cannot.cross.land': '⛔ الحدود البحرية لا يمكنها عبور اليابسة!',
  'draw.region.created': 'تم إنشاء "{name}" ({count} نقطة)',
  'draw.clipped.to.land': '· مقصوصة على اليابسة',
  'draw.clipped.to.sea': '· مقصوصة على البحر',
  'draw.clipped.regions': '· مقصوصة ضد المناطق',
  'draw.region.removed': 'تم حذف المنطقة',
  'draw.regions.cleared': 'تم حذف جميع المناطق',

  // Edit mode
  'edit.mode': 'وضع التحرير',
  'edit.editing': 'جاري التحرير',
  'edit.vertices': 'رؤوس',
  'edit.drag': 'اسحب للتحريك',
  'edit.dblclick': 'نقر مزدوج للحذف',
  'edit.midpoint': 'انقر على المنتصف للإضافة',
  'edit.vertex.added': 'تمت إضافة الرأس',
  'edit.vertex.removed': 'تم حذف الرأس',
  'edit.min.vertices': 'لا يمكن الحذف: الحد الأدنى 3 رؤوس',
  'edit.clipped': 'تم قص المنطقة للنطاق الصالح',
  'edit.done': 'اكتمل التحرير',

  // Annotations
  'ann.empty': 'لا توجد تعليقات.',
  'ann.removeall': '🗑️ حذف الكل',

  // Import
  'import.hint': 'تحميل حدود GeoJSON مخصصة.',

  // Export
  'export.format': 'الصيغة',
  'export.png': 'صورة PNG',
  'export.pdf': 'مستند PDF',
  'export.svg': 'متجه SVG',
  'export.width': 'العرض',
  'export.height': 'الارتفاع',
  'export.page': 'حجم الصفحة',
  'export.custom.mm': 'مخصص (مم)',
  'export.orientation': 'الاتجاه',
  'export.landscape': 'أفقي',
  'export.portrait': 'عمودي',
  'export.dpi': 'DPI',
  'export.view.info': '📐 <b>يصدر المنطقة المرئية.</b> حرّك وكبّر لتأطير الخريطة.',
  'export.world': '🌍 العالم',
  'export.fit': '📐 ملاءمة',
  'export.button': '💾 تصدير العرض الحالي',
  'export.modal.title': '⏳ جاري التصدير',
  'export.preparing': 'جاري تحضير التصدير...',
  'export.rendering.tiles': 'جاري رسم البلاطات...',
  'export.rendering.poly': 'جاري رسم الحدود...',
  'export.generating': 'جاري إنشاء الملف...',
  'export.done': 'تم!',

  // Banners
  'banner.text': '✏️ انقر على الخريطة لوضع النص',
  'banner.flag.select': '🏴 اختر علماً أولاً',
  'banner.flag.place': '🏴 انقر لوضع {name}',
  'banner.custom.place': '📁 انقر لوضع {name}',
  'banner.draw': '🖊️ انقر للرسم، أو اختر منطقة للتحرير',
  'banner.cancel': '✕',

  // Status messages
  'status.ready': 'جاهز',
  'status.loading': 'جاري تحميل {year}...',
  'status.loaded': '{year}: {count} منطقة ✓',
  'status.cached': '{year}: {count} منطقة (مخزنة) ✓',
  'status.error': 'خطأ في تحميل {year}: {msg}',
  'status.nation.selected': 'تم تحديد {count} دولة',
  'status.nations.selected': 'تم تحديد {count} دول',
  'status.all.selected': 'تم تحديد جميع الـ {count} دول',
  'status.inverted': 'تم عكس التحديد ({count} محدد)',
  'status.deselected': 'تم إلغاء التحديد',
  'status.select.nation.first': 'حدد الدول أولاً',
  'status.color.applied': 'تم تطبيق اللون {color} على {count} دولة',
  'status.colors.reset': 'تمت إعادة تعيين جميع الألوان',
  'status.text.placed': 'تم وضع النص "{text}"',
  'status.flag.select.first': 'اختر علماً أولاً',
  'status.flag.placed': 'تم وضع {name}',
  'status.custom.added': 'تمت إضافة العلم المخصص "{name}"',
  'status.custom.removed': 'تم حذف العلم المخصص',
  'status.format.unsupported': 'صيغة الملف غير مدعومة',
  'status.ann.removed': 'تم حذف التعليق',
  'status.ann.cleared': 'تم حذف جميع التعليقات',
  'status.imported': 'تم استيراد {count} عنصر',

  // Loading
  'loading.text': 'جاري التحميل...',

  // Countries
  'country.us': 'الولايات المتحدة',
  'country.gb': 'المملكة المتحدة',
  'country.fr': 'فرنسا',
  'country.de': 'ألمانيا',
  'country.it': 'إيطاليا',
  'country.jp': 'اليابان',
  'country.ru': 'روسيا',
  'country.cn': 'الصين',
  'country.ca': 'كندا',
  'country.au': 'أستراليا',
  'country.br': 'البرازيل',
  'country.in': 'الهند',
  'country.es': 'إسبانيا',
  'country.pt': 'البرتغال',
  'country.nl': 'هولندا',
  'country.be': 'بلجيكا',
  'country.pl': 'بولندا',
  'country.tr': 'تركيا',
  'country.mx': 'المكسيك',
  'country.ar': 'الأرجنتين',
  'country.se': 'السويد',
  'country.no': 'النرويج',
  'country.fi': 'فنلندا',
  'country.dk': 'الدنمارك',
  'country.gr': 'اليونان',
  'country.at': 'النمسا',
  'country.hu': 'المجر',
  'country.ro': 'رومانيا',
  'country.bg': 'بلغاريا',
  'country.rs': 'صربيا',
  'country.hr': 'كرواتيا',
  'country.ch': 'سويسرا',
  'country.ie': 'أيرلندا',
  'country.za': 'جنوب أفريقيا',
  'country.eg': 'مصر',
  'country.sa': 'السعودية',
  'country.ir': 'إيران',
  'country.iq': 'العراق',
  'country.th': 'تايلاند',
  'country.kr': 'كوريا الجنوبية',
  'country.nz': 'نيوزيلندا',
  'country.ua': 'أوكرانيا',
  'country.cu': 'كوبا',
  'country.et': 'إثيوبيا',
  'country.ng': 'نيجيريا',
  'country.pk': 'باكستان',
  'country.af': 'أفغانستان',
  'country.cl': 'تشيلي',
  'country.co': 'كولومبيا',
  'country.pe': 'بيرو',
  'country.ve': 'فنزويلا',
  'country.dz': 'الجزائر',
  'country.ma': 'المغرب',
  'country.ly': 'ليبيا',
  'country.sd': 'السودان',
  'country.tn': 'تونس',
  'country.sy': 'سوريا',
  'country.jo': 'الأردن',
  'country.lb': 'لبنان',
  'country.il': 'إسرائيل',
  'country.mm': 'ميانمار',
  'country.vn': 'فيتنام',
  'country.ph': 'الفلبين',
  'country.id': 'إندونيسيا',
  'country.my': 'ماليزيا',
  'country.bd': 'بنغلاديش',
  'country.lk': 'سريلانكا',
  'country.ke': 'كينيا'
});