// lang-ru.js — Russian translations
registerLanguage('ru', {
  // Header
  'header.title': 'Создатель Исторических Карт для <b>Настольных Игр</b>',

  // Year formatting
  'year.bc': 'до н.э.',
  'year.ad': 'н.э.',

  // Eras
  'era.prehistory': 'Доисторический период',
  'era.antiquity': 'Античность',
  'era.firstmill': 'Первое тысячелетие',
  'era.medieval': 'Средневековье',
  'era.earlymodern': 'Раннее Новое время',
  'era.nineteenth': 'XIX век',
  'era.twentieth': 'XX век',
  'era.twentyfirst': 'XXI век',

  // Panels
  'panel.year': '📅 Исторический год',
  'panel.style': '🎨 Стиль карты и границы',
  'panel.colors': '🏳️ Цвета стран',
  'panel.tools': '🛠️ Инструменты',
  'panel.annotations': '📋 Аннотации',
  'panel.import': '📂 Импорт GeoJSON',
  'panel.export': '💾 Экспорт',

  // Basemaps
  'basemap.label': 'Базовая карта',
  'basemap.physical': 'Физическая',
  'basemap.relief': 'Рельеф',
  'basemap.natgeo': 'National Geographic',
  'basemap.topo': 'Топографическая',
  'basemap.satellite': 'Спутник',
  'basemap.dark': 'Тёмная',
  'basemap.watercolor': 'Акварель',
  'basemap.none': 'Нет',

  // Border styles
  'border.style.label': 'Стиль границ',
  'border.solid': 'Сплошная',
  'border.dashed': 'Штриховая',
  'border.dotted': 'Пунктирная',
  'border.dashdot': 'Штрих-пунктир',
  'border.longdash': 'Длинный штрих',
  'border.double': 'Двойная',
  'border.sketch': 'Эскиз',
  'border.railroad': 'Железнодорожная',
  'border.desc.solid': 'Чистая сплошная линия',
  'border.desc.dashed': 'Классическая штриховая',
  'border.desc.dotted': 'Точечный узор',
  'border.desc.dashdot': 'Штрих-пунктирный узор',
  'border.desc.longdash': 'Длинные штрихи',
  'border.desc.double': 'Двойная линия',
  'border.desc.sketch': 'Нарисованный от руки стиль',
  'border.desc.railroad': 'Железнодорожный стиль',
  'border.width': 'Толщина границ',
  'border.px': 'пикс',
  'border.color': 'Цвет границ',
  'fill.opacity': 'Прозрачность заливки',

  // Colors panel
  'colors.selected': 'Выбранные страны',
  'colors.hint': 'Клик = выбор · Ctrl+Клик = множественный · Shift+Клик = диапазон',
  'colors.empty': 'Нажмите на страны на карте',
  'colors.all': '✅ Все',
  'colors.invert': '🔄 Инверсия',
  'colors.none': '✖ Очистить',
  'colors.apply.label': 'Применить цвет:',
  'colors.custom.label': 'Пользовательский:',
  'colors.apply': 'Применить',
  'colors.reset': '↺ Сброс',

  // Tools
  'tool.navigate': '🖱️ Навигация',
  'tool.text': '✏️ Текст',
  'tool.flag': '🏴 Флаг',
  'tool.draw': '🖊️ Рисование',

  // Text tool
  'text.label': 'Текст',
  'text.placeholder': 'Введите текст...',
  'text.size': 'Размер',
  'text.color': 'Цвет',
  'text.bold': 'Жирный',
  'text.outline': 'Контур',
  'text.rotation': 'Поворот',

  // Flag tool
  'flag.shape': 'Форма флага',
  'flag.circle': '🔵 Круглый',
  'flag.rect': '🟦 Прямоугольный',
  'flag.search': 'Поиск',
  'flag.search.placeholder': 'Искать страну...',
  'flag.size': 'Размер',
  'flag.upload.title': 'Загрузить свой флаг',
  'flag.upload.desc': 'PNG, SVG, JPG',
  'flag.name.placeholder': 'Название флага...',
  'flag.add': '➕ Добавить',
  'flag.builtin': 'Встроенные флаги',
  'flag.custom.section': 'Пользовательские флаги',
  'flag.select.hint': '👆 Выберите, затем нажмите на карту',
  'flag.selected': 'Выбрано: {name}',

  // Draw tool
  'draw.world.mode': 'Режим мира',
  'draw.world.existing': '🌍 Существующий',
  'draw.world.empty': '📄 Пустой',
  'draw.border.type': 'Тип границы',
  'draw.type.land': '🏔️ Суша',
  'draw.type.sea': '🌊 Море',
  'draw.region.name': 'Название региона',
  'draw.region.placeholder': 'Новый регион',
  'draw.region.color': 'Цвет региона',
  'draw.start': '✏️ Начать рисование',
  'draw.undo': '↩️ Отмена',
  'draw.cancel': '✕ Отмена',
  'draw.finish': '✓ Завершить',
  'draw.info.land.desc': 'Обрезается по береговой линии, только на суше.',
  'draw.info.sea.desc': 'Обрезается по береговой линии, только на море.',
  'draw.info.overlap.desc': 'Автоматическая обрезка по существующим регионам.',
  'draw.regions.title': 'Пользовательские регионы',
  'draw.regions.empty': 'Регионы не созданы.',
  'draw.regions.clear': '🗑️ Удалить все',

  // Draw status messages
  'draw.loading.coastline': 'Загрузка береговой линии...',
  'draw.mode.empty': 'Режим пустого мира — рисуйте свои границы',
  'draw.mode.existing': 'Режим существующих границ — исторические границы загружены',
  'draw.mode.land.hint': 'Граница суши: будет обрезана по береговой линии',
  'draw.mode.sea.hint': 'Морская граница: не может пересекать сушу',
  'draw.started': 'Нажимайте для добавления точек, двойной клик или первая точка для завершения',
  'draw.points': 'Точки: {count}',
  'draw.point.removed': 'Точка удалена',
  'draw.cancelled': 'Рисование отменено',
  'draw.need.3.points': 'Необходимо минимум 3 точки',
  'draw.fully.outside': 'Регион полностью за пределами допустимой области (суша/море)',
  'draw.snapped.region': 'Привязано к региону',
  'draw.snapped.coast.land': 'Привязано к берегу (режим суши)',
  'draw.snapped.coast.sea': 'Привязано к берегу (режим моря)',
  'draw.cannot.cross.land': '⛔ Морская граница не может пересекать сушу!',
  'draw.region.created': '"{name}" создан ({count} точек)',
  'draw.clipped.to.land': '· обрезано по суше',
  'draw.clipped.to.sea': '· обрезано по морю',
  'draw.clipped.regions': '· обрезано по регионам',
  'draw.region.removed': 'Регион удалён',
  'draw.regions.cleared': 'Все регионы удалены',

  // Edit mode
  'edit.mode': 'Режим редактирования',
  'edit.editing': 'Редактирование',
  'edit.vertices': 'вершин',
  'edit.drag': 'Перетащите для перемещения',
  'edit.dblclick': 'Двойной клик для удаления',
  'edit.midpoint': 'Клик на середину для добавления',
  'edit.vertex.added': 'Вершина добавлена',
  'edit.vertex.removed': 'Вершина удалена',
  'edit.min.vertices': 'Невозможно удалить: минимум 3 вершины',
  'edit.clipped': 'Регион обрезан до допустимой области',
  'edit.done': 'Редактирование завершено',

  // Annotations
  'ann.empty': 'Нет аннотаций.',
  'ann.removeall': '🗑️ Удалить все',

  // Import
  'import.hint': 'Загрузить пользовательские GeoJSON границы.',

  // Export
  'export.format': 'Формат',
  'export.png': 'PNG изображение',
  'export.pdf': 'PDF документ',
  'export.svg': 'SVG вектор',
  'export.width': 'Ширина',
  'export.height': 'Высота',
  'export.page': 'Размер страницы',
  'export.custom.mm': 'Пользовательский (мм)',
  'export.orientation': 'Ориентация',
  'export.landscape': 'Альбомная',
  'export.portrait': 'Книжная',
  'export.dpi': 'DPI',
  'export.view.info': '📐 <b>Экспортирует видимую область.</b> Панорамируйте и масштабируйте.',
  'export.world': '🌍 Мир',
  'export.fit': '📐 Вписать',
  'export.button': '💾 Экспортировать текущий вид',
  'export.modal.title': '⏳ Экспорт',
  'export.preparing': 'Подготовка экспорта...',
  'export.rendering.tiles': 'Рендеринг тайлов...',
  'export.rendering.poly': 'Рендеринг границ...',
  'export.generating': 'Генерация файла...',
  'export.done': 'Готово!',

  // Banners
  'banner.text': '✏️ Нажмите на карту для размещения текста',
  'banner.flag.select': '🏴 Сначала выберите флаг',
  'banner.flag.place': '🏴 Нажмите для размещения {name}',
  'banner.custom.place': '📁 Нажмите для размещения {name}',
  'banner.draw': '🖊️ Нажмите для рисования или выберите регион для редактирования',
  'banner.cancel': '✕',

  // Status messages
  'status.ready': 'Готово',
  'status.loading': 'Загрузка {year}...',
  'status.loaded': '{year}: {count} территорий ✓',
  'status.cached': '{year}: {count} территорий (кэш) ✓',
  'status.error': 'Ошибка загрузки {year}: {msg}',
  'status.nation.selected': 'Выбрано {count} страна',
  'status.nations.selected': 'Выбрано {count} стран',
  'status.all.selected': 'Выбраны все {count} стран',
  'status.inverted': 'Выбор инвертирован ({count} выбрано)',
  'status.deselected': 'Выбор снят',
  'status.select.nation.first': 'Сначала выберите страны',
  'status.color.applied': 'Цвет {color} применён к {count} стране(ам)',
  'status.colors.reset': 'Все цвета сброшены',
  'status.text.placed': 'Текст "{text}" размещён',
  'status.flag.select.first': 'Сначала выберите флаг',
  'status.flag.placed': '{name} размещён',
  'status.custom.added': 'Пользовательский флаг "{name}" добавлен',
  'status.custom.removed': 'Пользовательский флаг удалён',
  'status.format.unsupported': 'Неподдерживаемый формат файла',
  'status.ann.removed': 'Аннотация удалена',
  'status.ann.cleared': 'Все аннотации удалены',
  'status.imported': 'Импортировано {count} объектов',

  // Loading
  'loading.text': 'Загрузка...',

  // Countries
  'country.us': 'США',
  'country.gb': 'Великобритания',
  'country.fr': 'Франция',
  'country.de': 'Германия',
  'country.it': 'Италия',
  'country.jp': 'Япония',
  'country.ru': 'Россия',
  'country.cn': 'Китай',
  'country.ca': 'Канада',
  'country.au': 'Австралия',
  'country.br': 'Бразилия',
  'country.in': 'Индия',
  'country.es': 'Испания',
  'country.pt': 'Португалия',
  'country.nl': 'Нидерланды',
  'country.be': 'Бельгия',
  'country.pl': 'Польша',
  'country.tr': 'Турция',
  'country.mx': 'Мексика',
  'country.ar': 'Аргентина',
  'country.se': 'Швеция',
  'country.no': 'Норвегия',
  'country.fi': 'Финляндия',
  'country.dk': 'Дания',
  'country.gr': 'Греция',
  'country.at': 'Австрия',
  'country.hu': 'Венгрия',
  'country.ro': 'Румыния',
  'country.bg': 'Болгария',
  'country.rs': 'Сербия',
  'country.hr': 'Хорватия',
  'country.ch': 'Швейцария',
  'country.ie': 'Ирландия',
  'country.za': 'ЮАР',
  'country.eg': 'Египет',
  'country.sa': 'Саудовская Аравия',
  'country.ir': 'Иран',
  'country.iq': 'Ирак',
  'country.th': 'Таиланд',
  'country.kr': 'Южная Корея',
  'country.nz': 'Новая Зеландия',
  'country.ua': 'Украина',
  'country.cu': 'Куба',
  'country.et': 'Эфиопия',
  'country.ng': 'Нигерия',
  'country.pk': 'Пакистан',
  'country.af': 'Афганистан',
  'country.cl': 'Чили',
  'country.co': 'Колумбия',
  'country.pe': 'Перу',
  'country.ve': 'Венесуэла',
  'country.dz': 'Алжир',
  'country.ma': 'Марокко',
  'country.ly': 'Ливия',
  'country.sd': 'Судан',
  'country.tn': 'Тунис',
  'country.sy': 'Сирия',
  'country.jo': 'Иордания',
  'country.lb': 'Ливан',
  'country.il': 'Израиль',
  'country.mm': 'Мьянма',
  'country.vn': 'Вьетнам',
  'country.ph': 'Филиппины',
  'country.id': 'Индонезия',
  'country.my': 'Малайзия',
  'country.bd': 'Бангладеш',
  'country.lk': 'Шри-Ланка',
  'country.ke': 'Кения'
});