// lang-es.js — Spanish translations
registerLanguage('es', {
  // Header
  'header.title': 'Creador de Mapas <b>Juegos de Mesa</b> Históricos',

  // Year formatting
  'year.bc': 'a.C.',
  'year.ad': 'd.C.',

  // Eras
  'era.prehistory': 'Prehistoria',
  'era.antiquity': 'Antigüedad',
  'era.firstmill': 'Primer Milenio',
  'era.medieval': 'Medieval',
  'era.earlymodern': 'Edad Moderna',
  'era.nineteenth': 'Siglo XIX',
  'era.twentieth': 'Siglo XX',
  'era.twentyfirst': 'Siglo XXI',

  // Panels
  'panel.year': '📅 Año Histórico',
  'panel.style': '🎨 Estilo de Mapa & Fronteras',
  'panel.colors': '🏳️ Colores de Naciones',
  'panel.tools': '🛠️ Herramientas',
  'panel.annotations': '📋 Anotaciones',
  'panel.import': '📂 Importar GeoJSON',
  'panel.export': '💾 Exportar',

  // Basemaps
  'basemap.label': 'Mapa Base',
  'basemap.physical': 'Físico',
  'basemap.relief': 'Relieve Sombreado',
  'basemap.natgeo': 'National Geographic',
  'basemap.topo': 'Topográfico',
  'basemap.satellite': 'Satélite',
  'basemap.dark': 'Oscuro',
  'basemap.watercolor': 'Acuarela',
  'basemap.none': 'Ninguno',

  // Border styles
  'border.style.label': 'Estilo de Fronteras',
  'border.solid': 'Sólido',
  'border.dashed': 'Discontinuo',
  'border.dotted': 'Punteado',
  'border.dashdot': 'Guion-Punto',
  'border.longdash': 'Guion Largo',
  'border.double': 'Doble',
  'border.sketch': 'Boceto',
  'border.railroad': 'Ferrocarril',
  'border.desc.solid': 'Línea sólida limpia',
  'border.desc.dashed': 'Discontinuo clásico',
  'border.desc.dotted': 'Patrón punteado',
  'border.desc.dashdot': 'Patrón guion-punto',
  'border.desc.longdash': 'Guiones largos',
  'border.desc.double': 'Línea doble',
  'border.desc.sketch': 'Estilo dibujado a mano',
  'border.desc.railroad': 'Estilo ferrocarril',
  'border.width': 'Ancho de Fronteras',
  'border.px': 'px',
  'border.color': 'Color de Fronteras',
  'fill.opacity': 'Opacidad de Relleno',

  // Colors panel
  'colors.selected': 'Naciones Seleccionadas',
  'colors.hint': 'Clic = selección · Ctrl+Clic = múltiple · Shift+Clic = rango',
  'colors.empty': 'Haga clic en las naciones del mapa',
  'colors.all': '✅ Todas',
  'colors.invert': '🔄 Invertir',
  'colors.none': '✖ Ninguna',
  'colors.apply.label': 'Aplicar color:',
  'colors.custom.label': 'Personalizado:',
  'colors.apply': 'Aplicar',
  'colors.reset': '↺ Restablecer',

  // Tools
  'tool.navigate': '🖱️ Navegar',
  'tool.text': '✏️ Texto',
  'tool.flag': '🏴 Bandera',
  'tool.draw': '🖊️ Dibujar',

  // Text tool
  'text.label': 'Texto',
  'text.placeholder': 'Introducir texto...',
  'text.size': 'Tamaño',
  'text.color': 'Color',
  'text.bold': 'Negrita',
  'text.outline': 'Contorno',
  'text.rotation': 'Rotación',

  // Flag tool
  'flag.shape': 'Forma de Bandera',
  'flag.circle': '🔵 Circular',
  'flag.rect': '🟦 Rectangular',
  'flag.search': 'Buscar',
  'flag.search.placeholder': 'Buscar país...',
  'flag.size': 'Tamaño',
  'flag.upload.title': 'Subir bandera personalizada',
  'flag.upload.desc': 'PNG, SVG, JPG',
  'flag.name.placeholder': 'Nombre de bandera...',
  'flag.add': '➕ Añadir',
  'flag.builtin': 'Banderas Integradas',
  'flag.custom.section': 'Banderas Personalizadas',
  'flag.select.hint': '👆 Seleccione, luego clic en el mapa',
  'flag.selected': 'Seleccionada: {name}',

  // Draw tool
  'draw.world.mode': 'Modo Mundo',
  'draw.world.existing': '🌍 Existente',
  'draw.world.empty': '📄 Vacío',
  'draw.border.type': 'Tipo de Frontera',
  'draw.type.land': '🏔️ Terrestre',
  'draw.type.sea': '🌊 Marítimo',
  'draw.region.name': 'Nombre de Región',
  'draw.region.placeholder': 'Nueva Región',
  'draw.region.color': 'Color de Región',
  'draw.start': '✏️ Iniciar Dibujo',
  'draw.undo': '↩️ Deshacer',
  'draw.cancel': '✕ Cancelar',
  'draw.finish': '✓ Terminar',
  'draw.info.land.desc': 'Recortado en la costa, solo en tierra.',
  'draw.info.sea.desc': 'Recortado en la costa, solo en mar.',
  'draw.info.overlap.desc': 'Recorte automático contra regiones existentes.',
  'draw.regions.title': 'Regiones Personalizadas',
  'draw.regions.empty': 'No hay regiones creadas.',
  'draw.regions.clear': '🗑️ Eliminar Todas',

  // Draw status messages
  'draw.loading.coastline': 'Cargando líneas costeras...',
  'draw.mode.empty': 'Modo mundo vacío — dibuja tus fronteras',
  'draw.mode.existing': 'Modo fronteras existentes — fronteras históricas cargadas',
  'draw.mode.land.hint': 'Frontera terrestre: se recortará en la costa',
  'draw.mode.sea.hint': 'Frontera marítima: no puede cruzar tierra',
  'draw.started': 'Clic para añadir puntos, doble clic o primer punto para terminar',
  'draw.points': 'Puntos: {count}',
  'draw.point.removed': 'Punto eliminado',
  'draw.cancelled': 'Dibujo cancelado',
  'draw.need.3.points': 'Se necesitan al menos 3 puntos',
  'draw.fully.outside': 'Región completamente fuera del área válida (tierra/mar)',
  'draw.snapped.region': 'Ajustado a la región',
  'draw.snapped.coast.land': 'Ajustado a la costa (modo tierra)',
  'draw.snapped.coast.sea': 'Ajustado a la costa (modo mar)',
  'draw.cannot.cross.land': '⛔ ¡La frontera marítima no puede cruzar tierra!',
  'draw.region.created': '"{name}" creada ({count} puntos)',
  'draw.clipped.to.land': '· recortada a tierra',
  'draw.clipped.to.sea': '· recortada a mar',
  'draw.clipped.regions': '· recortada contra regiones',
  'draw.region.removed': 'Región eliminada',
  'draw.regions.cleared': 'Todas las regiones eliminadas',

  // Edit mode
  'edit.mode': 'Modo Edición',
  'edit.editing': 'Editando',
  'edit.vertices': 'vértices',
  'edit.drag': 'Arrastrar para mover',
  'edit.dblclick': 'Doble clic para eliminar',
  'edit.midpoint': 'Clic en punto medio para añadir',
  'edit.vertex.added': 'Vértice añadido',
  'edit.vertex.removed': 'Vértice eliminado',
  'edit.min.vertices': 'No se puede eliminar: mínimo 3 vértices',
  'edit.clipped': 'Región recortada al área válida',
  'edit.done': 'Edición completada',

  // Annotations
  'ann.empty': 'Sin anotaciones.',
  'ann.removeall': '🗑️ Eliminar Todas',

  // Import
  'import.hint': 'Cargar fronteras GeoJSON personalizadas.',

  // Export
  'export.format': 'Formato',
  'export.png': 'Imagen PNG',
  'export.pdf': 'Documento PDF',
  'export.svg': 'Vector SVG',
  'export.width': 'Ancho',
  'export.height': 'Alto',
  'export.page': 'Tamaño de Página',
  'export.custom.mm': 'Personalizado (mm)',
  'export.orientation': 'Orientación',
  'export.landscape': 'Horizontal',
  'export.portrait': 'Vertical',
  'export.dpi': 'DPI',
  'export.view.info': '📐 <b>Exporta el área visible.</b> Desplaza y amplía para encuadrar.',
  'export.world': '🌍 Mundo',
  'export.fit': '📐 Ajustar',
  'export.button': '💾 Exportar Vista Actual',
  'export.modal.title': '⏳ Exportando',
  'export.preparing': 'Preparando exportación...',
  'export.rendering.tiles': 'Renderizando teselas...',
  'export.rendering.poly': 'Renderizando fronteras...',
  'export.generating': 'Generando archivo...',
  'export.done': '¡Completado!',

  // Banners
  'banner.text': '✏️ Clic en el mapa para colocar texto',
  'banner.flag.select': '🏴 Seleccione primero una bandera',
  'banner.flag.place': '🏴 Clic para colocar {name}',
  'banner.custom.place': '📁 Clic para colocar {name}',
  'banner.draw': '🖊️ Clic para dibujar, o seleccione una región para editar',
  'banner.cancel': '✕',

  // Status messages
  'status.ready': 'Listo',
  'status.loading': 'Cargando {year}...',
  'status.loaded': '{year}: {count} territorios ✓',
  'status.cached': '{year}: {count} territorios (caché) ✓',
  'status.error': 'Error cargando {year}: {msg}',
  'status.nation.selected': '{count} nación seleccionada',
  'status.nations.selected': '{count} naciones seleccionadas',
  'status.all.selected': 'Todas las {count} naciones seleccionadas',
  'status.inverted': 'Selección invertida ({count} seleccionadas)',
  'status.deselected': 'Selección anulada',
  'status.select.nation.first': 'Seleccione primero las naciones',
  'status.color.applied': 'Color {color} aplicado a {count} nación(es)',
  'status.colors.reset': 'Todos los colores restablecidos',
  'status.text.placed': 'Texto "{text}" colocado',
  'status.flag.select.first': 'Seleccione primero una bandera',
  'status.flag.placed': '{name} colocada',
  'status.custom.added': 'Bandera personalizada "{name}" añadida',
  'status.custom.removed': 'Bandera personalizada eliminada',
  'status.format.unsupported': 'Formato de archivo no soportado',
  'status.ann.removed': 'Anotación eliminada',
  'status.ann.cleared': 'Todas las anotaciones eliminadas',
  'status.imported': '{count} elementos importados',

  // Loading
  'loading.text': 'Cargando...',

  // Countries
  'country.us': 'Estados Unidos',
  'country.gb': 'Reino Unido',
  'country.fr': 'Francia',
  'country.de': 'Alemania',
  'country.it': 'Italia',
  'country.jp': 'Japón',
  'country.ru': 'Rusia',
  'country.cn': 'China',
  'country.ca': 'Canadá',
  'country.au': 'Australia',
  'country.br': 'Brasil',
  'country.in': 'India',
  'country.es': 'España',
  'country.pt': 'Portugal',
  'country.nl': 'Países Bajos',
  'country.be': 'Bélgica',
  'country.pl': 'Polonia',
  'country.tr': 'Turquía',
  'country.mx': 'México',
  'country.ar': 'Argentina',
  'country.se': 'Suecia',
  'country.no': 'Noruega',
  'country.fi': 'Finlandia',
  'country.dk': 'Dinamarca',
  'country.gr': 'Grecia',
  'country.at': 'Austria',
  'country.hu': 'Hungría',
  'country.ro': 'Rumania',
  'country.bg': 'Bulgaria',
  'country.rs': 'Serbia',
  'country.hr': 'Croacia',
  'country.ch': 'Suiza',
  'country.ie': 'Irlanda',
  'country.za': 'Sudáfrica',
  'country.eg': 'Egipto',
  'country.sa': 'Arabia Saudita',
  'country.ir': 'Irán',
  'country.iq': 'Irak',
  'country.th': 'Tailandia',
  'country.kr': 'Corea del Sur',
  'country.nz': 'Nueva Zelanda',
  'country.ua': 'Ucrania',
  'country.cu': 'Cuba',
  'country.et': 'Etiopía',
  'country.ng': 'Nigeria',
  'country.pk': 'Pakistán',
  'country.af': 'Afganistán',
  'country.cl': 'Chile',
  'country.co': 'Colombia',
  'country.pe': 'Perú',
  'country.ve': 'Venezuela',
  'country.dz': 'Argelia',
  'country.ma': 'Marruecos',
  'country.ly': 'Libia',
  'country.sd': 'Sudán',
  'country.tn': 'Túnez',
  'country.sy': 'Siria',
  'country.jo': 'Jordania',
  'country.lb': 'Líbano',
  'country.il': 'Israel',
  'country.mm': 'Myanmar',
  'country.vn': 'Vietnam',
  'country.ph': 'Filipinas',
  'country.id': 'Indonesia',
  'country.my': 'Malasia',
  'country.bd': 'Bangladesh',
  'country.lk': 'Sri Lanka',
  'country.ke': 'Kenia'
});