// lang-it.js — Italian translations
registerLanguage('it', {
  // Header
  'header.title': 'Creatore Mappe <b>Giochi da Tavolo</b> Storiche',

  // Year formatting
  'year.bc': 'a.C.',
  'year.ad': 'd.C.',

  // Eras
  'era.prehistory': 'Preistoria',
  'era.antiquity': 'Antichità',
  'era.firstmill': 'Primo Millennio',
  'era.medieval': 'Medioevo',
  'era.earlymodern': 'Età Moderna',
  'era.nineteenth': 'XIX Secolo',
  'era.twentieth': 'XX Secolo',
  'era.twentyfirst': 'XXI Secolo',

  // Panels
  'panel.year': '📅 Anno Storico',
  'panel.style': '🎨 Stile Mappa & Confini',
  'panel.colors': '🏳️ Colori Nazioni',
  'panel.tools': '🛠️ Strumenti',
  'panel.annotations': '📋 Annotazioni',
  'panel.import': '📂 Importa GeoJSON',
  'panel.export': '💾 Esporta',

  // Basemaps
  'basemap.label': 'Mappa di Base',
  'basemap.physical': 'Fisica',
  'basemap.relief': 'Rilievo Ombreggiato',
  'basemap.natgeo': 'National Geographic',
  'basemap.topo': 'Topografica',
  'basemap.satellite': 'Satellite',
  'basemap.dark': 'Scura',
  'basemap.watercolor': 'Acquerello',
  'basemap.none': 'Nessuna',

  // Border styles
  'border.style.label': 'Stile Confini',
  'border.solid': 'Continuo',
  'border.dashed': 'Tratteggiato',
  'border.dotted': 'Puntinato',
  'border.dashdot': 'Tratto-Punto',
  'border.longdash': 'Tratto Lungo',
  'border.double': 'Doppio',
  'border.sketch': 'Disegnato',
  'border.railroad': 'Ferrovia',
  'border.desc.solid': 'Linea continua pulita',
  'border.desc.dashed': 'Tratteggio classico',
  'border.desc.dotted': 'Motivo a punti',
  'border.desc.dashdot': 'Motivo tratto-punto',
  'border.desc.longdash': 'Tratti lunghi',
  'border.desc.double': 'Linea doppia',
  'border.desc.sketch': 'Stile disegnato a mano',
  'border.desc.railroad': 'Stile ferrovia',
  'border.width': 'Spessore Confini',
  'border.px': 'px',
  'border.color': 'Colore Confini',
  'fill.opacity': 'Opacità Riempimento',

  // Colors panel
  'colors.selected': 'Nazioni Selezionate',
  'colors.hint': 'Click = seleziona · Ctrl+Click = multiplo · Shift+Click = intervallo',
  'colors.empty': 'Clicca sulle nazioni nella mappa',
  'colors.all': '✅ Tutte',
  'colors.invert': '🔄 Inverti',
  'colors.none': '✖ Nessuna',
  'colors.apply.label': 'Applica colore:',
  'colors.custom.label': 'Personalizzato:',
  'colors.apply': 'Applica',
  'colors.reset': '↺ Reset',

  // Tools
  'tool.navigate': '🖱️ Naviga',
  'tool.text': '✏️ Testo',
  'tool.flag': '🏴 Bandiera',
  'tool.draw': '🖊️ Disegna',

  // Text tool
  'text.label': 'Testo',
  'text.placeholder': 'Inserisci testo...',
  'text.size': 'Dimensione',
  'text.color': 'Colore',
  'text.bold': 'Grassetto',
  'text.outline': 'Contorno',
  'text.rotation': 'Rotazione',

  // Flag tool
  'flag.shape': 'Forma Bandiera',
  'flag.circle': '🔵 Tonda',
  'flag.rect': '🟦 Rettangolare',
  'flag.search': 'Cerca',
  'flag.search.placeholder': 'Cerca paese...',
  'flag.size': 'Dimensione',
  'flag.upload.title': 'Carica bandiera personalizzata',
  'flag.upload.desc': 'PNG, SVG, JPG',
  'flag.name.placeholder': 'Nome bandiera...',
  'flag.add': '➕ Aggiungi',
  'flag.builtin': 'Bandiere Predefinite',
  'flag.custom.section': 'Bandiere Personalizzate',
  'flag.select.hint': '👆 Seleziona, poi clicca sulla mappa',
  'flag.selected': 'Selezionata: {name}',

  // Draw tool
  'draw.world.mode': 'Modalità Mondo',
  'draw.world.existing': '🌍 Esistente',
  'draw.world.empty': '📄 Vuoto',
  'draw.border.type': 'Tipo Confine',
  'draw.type.land': '🏔️ Terrestre',
  'draw.type.sea': '🌊 Marittimo',
  'draw.region.name': 'Nome Regione',
  'draw.region.placeholder': 'Nuova Regione',
  'draw.region.color': 'Colore Regione',
  'draw.start': '✏️ Inizia Disegno',
  'draw.undo': '↩️ Annulla',
  'draw.cancel': '✕ Annulla',
  'draw.finish': '✓ Completa',
  'draw.info.land.desc': 'Ritagliato sulla costa, solo sulla terra.',
  'draw.info.sea.desc': 'Ritagliato sulla costa, solo sul mare.',
  'draw.info.overlap.desc': 'Ritaglio automatico contro regioni esistenti.',
  'draw.regions.title': 'Regioni Personalizzate',
  'draw.regions.empty': 'Nessuna regione creata.',
  'draw.regions.clear': '🗑️ Rimuovi Tutte',

  // Draw status messages
  'draw.loading.coastline': 'Caricamento linee costiere...',
  'draw.mode.empty': 'Mondo vuoto — disegna i tuoi confini',
  'draw.mode.existing': 'Confini esistenti — confini storici caricati',
  'draw.mode.land.hint': 'Confine terrestre: verrà ritagliato sulla costa',
  'draw.mode.sea.hint': 'Confine marittimo: non può attraversare la terra',
  'draw.started': 'Clicca per aggiungere punti, doppio-click o primo punto per completare',
  'draw.points': 'Punti: {count}',
  'draw.point.removed': 'Punto rimosso',
  'draw.cancelled': 'Disegno annullato',
  'draw.need.3.points': 'Servono almeno 3 punti',
  'draw.fully.outside': 'Regione interamente fuori dall\'area valida (terra/mare)',
  'draw.snapped.region': 'Agganciato alla regione',
  'draw.snapped.coast.land': 'Agganciato alla costa (modalità terra)',
  'draw.snapped.coast.sea': 'Agganciato alla costa (modalità mare)',
  'draw.cannot.cross.land': '⛔ Il confine marittimo non può attraversare la terra!',
  'draw.region.created': '"{name}" creata ({count} punti)',
  'draw.clipped.to.land': '· ritagliata sulla terra',
  'draw.clipped.to.sea': '· ritagliata sul mare',
  'draw.clipped.regions': '· ritagliata contro regioni',
  'draw.region.removed': 'Regione rimossa',
  'draw.regions.cleared': 'Tutte le regioni rimosse',

  // Edit mode
  'edit.mode': 'Modalità Modifica',
  'edit.editing': 'Modifica',
  'edit.vertices': 'vertici',
  'edit.drag': 'Trascina per spostare',
  'edit.dblclick': 'Doppio-click per rimuovere',
  'edit.midpoint': 'Click su punto medio per aggiungere',
  'edit.vertex.added': 'Vertice aggiunto',
  'edit.vertex.removed': 'Vertice rimosso',
  'edit.min.vertices': 'Impossibile rimuovere: minimo 3 vertici',
  'edit.clipped': 'Regione ritagliata nell\'area valida',
  'edit.done': 'Modifica completata',

  // Annotations
  'ann.empty': 'Nessuna annotazione.',
  'ann.removeall': '🗑️ Rimuovi Tutte',

  // Import
  'import.hint': 'Carica confini GeoJSON personalizzati.',

  // Export
  'export.format': 'Formato',
  'export.png': 'Immagine PNG',
  'export.pdf': 'Documento PDF',
  'export.svg': 'Vettoriale SVG',
  'export.width': 'Larghezza',
  'export.height': 'Altezza',
  'export.page': 'Dimensione Pagina',
  'export.custom.mm': 'Personalizzato (mm)',
  'export.orientation': 'Orientamento',
  'export.landscape': 'Orizzontale',
  'export.portrait': 'Verticale',
  'export.dpi': 'DPI',
  'export.view.info': '📐 <b>Esporta l\'area visibile.</b> Sposta e zooma per inquadrare la mappa.',
  'export.world': '🌍 Mondo',
  'export.fit': '📐 Adatta',
  'export.button': '💾 Esporta Vista Corrente',
  'export.modal.title': '⏳ Esportazione',
  'export.preparing': 'Preparazione esportazione...',
  'export.rendering.tiles': 'Rendering tile mappa...',
  'export.rendering.poly': 'Rendering confini...',
  'export.generating': 'Generazione file...',
  'export.done': 'Completato!',

  // Banners
  'banner.text': '✏️ Clicca sulla mappa per posizionare il testo',
  'banner.flag.select': '🏴 Seleziona prima una bandiera',
  'banner.flag.place': '🏴 Clicca per posizionare {name}',
  'banner.custom.place': '📁 Clicca per posizionare {name}',
  'banner.draw': '🖊️ Clicca per iniziare a disegnare, o seleziona una regione da modificare',
  'banner.cancel': '✕',

  // Status messages
  'status.ready': 'Pronto',
  'status.loading': 'Caricamento {year}...',
  'status.loaded': '{year}: {count} territori ✓',
  'status.cached': '{year}: {count} territori (cache) ✓',
  'status.error': 'Errore caricamento {year}: {msg}',
  'status.nation.selected': '{count} nazione selezionata',
  'status.nations.selected': '{count} nazioni selezionate',
  'status.all.selected': 'Tutte le {count} nazioni selezionate',
  'status.inverted': 'Selezione invertita ({count} selezionate)',
  'status.deselected': 'Selezione annullata',
  'status.select.nation.first': 'Seleziona prima le nazioni',
  'status.color.applied': 'Colore {color} applicato a {count} nazione/i',
  'status.colors.reset': 'Tutti i colori resettati',
  'status.text.placed': 'Testo "{text}" posizionato',
  'status.flag.select.first': 'Seleziona prima una bandiera',
  'status.flag.placed': '{name} posizionata',
  'status.custom.added': 'Bandiera personalizzata "{name}" aggiunta',
  'status.custom.removed': 'Bandiera personalizzata rimossa',
  'status.format.unsupported': 'Formato file non supportato',
  'status.ann.removed': 'Annotazione rimossa',
  'status.ann.cleared': 'Tutte le annotazioni rimosse',
  'status.imported': '{count} elementi importati',

  // Loading
  'loading.text': 'Caricamento...',

  // Countries (for flags)
  'country.us': 'Stati Uniti',
  'country.gb': 'Regno Unito',
  'country.fr': 'Francia',
  'country.de': 'Germania',
  'country.it': 'Italia',
  'country.jp': 'Giappone',
  'country.ru': 'Russia',
  'country.cn': 'Cina',
  'country.ca': 'Canada',
  'country.au': 'Australia',
  'country.br': 'Brasile',
  'country.in': 'India',
  'country.es': 'Spagna',
  'country.pt': 'Portogallo',
  'country.nl': 'Paesi Bassi',
  'country.be': 'Belgio',
  'country.pl': 'Polonia',
  'country.tr': 'Turchia',
  'country.mx': 'Messico',
  'country.ar': 'Argentina',
  'country.se': 'Svezia',
  'country.no': 'Norvegia',
  'country.fi': 'Finlandia',
  'country.dk': 'Danimarca',
  'country.gr': 'Grecia',
  'country.at': 'Austria',
  'country.hu': 'Ungheria',
  'country.ro': 'Romania',
  'country.bg': 'Bulgaria',
  'country.rs': 'Serbia',
  'country.hr': 'Croazia',
  'country.ch': 'Svizzera',
  'country.ie': 'Irlanda',
  'country.za': 'Sudafrica',
  'country.eg': 'Egitto',
  'country.sa': 'Arabia Saudita',
  'country.ir': 'Iran',
  'country.iq': 'Iraq',
  'country.th': 'Thailandia',
  'country.kr': 'Corea del Sud',
  'country.nz': 'Nuova Zelanda',
  'country.ua': 'Ucraina',
  'country.cu': 'Cuba',
  'country.et': 'Etiopia',
  'country.ng': 'Nigeria',
  'country.pk': 'Pakistan',
  'country.af': 'Afghanistan',
  'country.cl': 'Cile',
  'country.co': 'Colombia',
  'country.pe': 'Perù',
  'country.ve': 'Venezuela',
  'country.dz': 'Algeria',
  'country.ma': 'Marocco',
  'country.ly': 'Libia',
  'country.sd': 'Sudan',
  'country.tn': 'Tunisia',
  'country.sy': 'Siria',
  'country.jo': 'Giordania',
  'country.lb': 'Libano',
  'country.il': 'Israele',
  'country.mm': 'Myanmar',
  'country.vn': 'Vietnam',
  'country.ph': 'Filippine',
  'country.id': 'Indonesia',
  'country.my': 'Malesia',
  'country.bd': 'Bangladesh',
  'country.lk': 'Sri Lanka',
  'country.ke': 'Kenya'
});