// lang-en.js — English translations
registerLanguage('en', {
  // Header
  'header.title': 'Historical <b>Board Game</b> Map Maker',

  // Year formatting
  'year.bc': 'BC',
  'year.ad': 'AD',

  // Eras
  'era.prehistory': 'Prehistory',
  'era.antiquity': 'Antiquity',
  'era.firstmill': 'First Millennium',
  'era.medieval': 'Medieval',
  'era.earlymodern': 'Early Modern',
  'era.nineteenth': '19th Century',
  'era.twentieth': '20th Century',
  'era.twentyfirst': '21st Century',

  // Panels
  'panel.year': '📅 Historical Year',
  'panel.style': '🎨 Map Style & Borders',
  'panel.colors': '🏳️ Nation Colors',
  'panel.tools': '🛠️ Tools',
  'panel.annotations': '📋 Annotations',
  'panel.import': '📂 Import GeoJSON',
  'panel.export': '💾 Export',

  // Basemaps
  'basemap.label': 'Base Map',
  'basemap.physical': 'Physical',
  'basemap.relief': 'Shaded Relief',
  'basemap.natgeo': 'National Geographic',
  'basemap.topo': 'Topographic',
  'basemap.satellite': 'Satellite',
  'basemap.dark': 'Dark',
  'basemap.watercolor': 'Watercolor',
  'basemap.none': 'None',

  // Border styles
  'border.style.label': 'Border Style',
  'border.solid': 'Solid',
  'border.dashed': 'Dashed',
  'border.dotted': 'Dotted',
  'border.dashdot': 'Dash-Dot',
  'border.longdash': 'Long Dash',
  'border.double': 'Double',
  'border.sketch': 'Sketch',
  'border.railroad': 'Railroad',
  'border.desc.solid': 'Clean solid line',
  'border.desc.dashed': 'Classic dashed',
  'border.desc.dotted': 'Dotted pattern',
  'border.desc.dashdot': 'Dash-dot pattern',
  'border.desc.longdash': 'Long dashes',
  'border.desc.double': 'Double line',
  'border.desc.sketch': 'Hand-drawn style',
  'border.desc.railroad': 'Railroad style',
  'border.width': 'Border Width',
  'border.px': 'px',
  'border.color': 'Border Color',
  'fill.opacity': 'Fill Opacity',

  // Colors panel
  'colors.selected': 'Selected Nations',
  'colors.hint': 'Click = select · Ctrl+Click = multi · Shift+Click = range',
  'colors.empty': 'Click on nations in the map',
  'colors.all': '✅ All',
  'colors.invert': '🔄 Invert',
  'colors.none': '✖ None',
  'colors.apply.label': 'Apply color:',
  'colors.custom.label': 'Custom:',
  'colors.apply': 'Apply',
  'colors.reset': '↺ Reset',

  // Tools
  'tool.navigate': '🖱️ Navigate',
  'tool.text': '✏️ Text',
  'tool.flag': '🏴 Flag',
  'tool.draw': '🖊️ Draw',

  // Text tool
  'text.label': 'Text',
  'text.placeholder': 'Enter text...',
  'text.size': 'Size',
  'text.color': 'Color',
  'text.bold': 'Bold',
  'text.outline': 'Outline',
  'text.rotation': 'Rotation',

  // Flag tool
  'flag.shape': 'Flag Shape',
  'flag.circle': '🔵 Circle',
  'flag.rect': '🟦 Rectangle',
  'flag.search': 'Search',
  'flag.search.placeholder': 'Search country...',
  'flag.size': 'Size',
  'flag.upload.title': 'Upload custom flag',
  'flag.upload.desc': 'PNG, SVG, JPG',
  'flag.name.placeholder': 'Flag name...',
  'flag.add': '➕ Add',
  'flag.builtin': 'Built-in Flags',
  'flag.custom.section': 'Custom Flags',
  'flag.select.hint': '👆 Select, then click on the map',
  'flag.selected': 'Selected: {name}',

  // Draw tool
  'draw.world.mode': 'World Mode',
  'draw.world.existing': '🌍 Existing',
  'draw.world.empty': '📄 Empty',
  'draw.border.type': 'Border Type',
  'draw.type.land': '🏔️ Land',
  'draw.type.sea': '🌊 Sea',
  'draw.region.name': 'Region Name',
  'draw.region.placeholder': 'New Region',
  'draw.region.color': 'Region Color',
  'draw.start': '✏️ Start Drawing',
  'draw.undo': '↩️ Undo',
  'draw.cancel': '✕ Cancel',
  'draw.finish': '✓ Finish',
  'draw.info.land.desc': 'Clipped to coastline, stays on land only.',
  'draw.info.sea.desc': 'Clipped to coastline, stays on sea only.',
  'draw.info.overlap.desc': 'Auto-clipped against existing regions.',
  'draw.regions.title': 'Custom Regions',
  'draw.regions.empty': 'No regions created.',
  'draw.regions.clear': '🗑️ Remove All',

  // Draw status messages
  'draw.loading.coastline': 'Loading coastline data...',
  'draw.mode.empty': 'Empty world mode — draw your own borders',
  'draw.mode.existing': 'Existing borders mode — historical borders loaded',
  'draw.mode.land.hint': 'Land border: will be clipped to coastline',
  'draw.mode.sea.hint': 'Sea border: cannot cross land',
  'draw.started': 'Click to add points, double-click or click first point to finish',
  'draw.points': 'Points: {count}',
  'draw.point.removed': 'Point removed',
  'draw.cancelled': 'Drawing cancelled',
  'draw.need.3.points': 'Need at least 3 points',
  'draw.fully.outside': 'Region entirely outside valid area (land/sea)',
  'draw.snapped.region': 'Snapped to region',
  'draw.snapped.coast.land': 'Snapped to coast (land mode)',
  'draw.snapped.coast.sea': 'Snapped to coast (sea mode)',
  'draw.cannot.cross.land': '⛔ Sea border cannot cross land!',
  'draw.region.created': '"{name}" created ({count} points)',
  'draw.clipped.to.land': '· clipped to land',
  'draw.clipped.to.sea': '· clipped to sea',
  'draw.clipped.regions': '· clipped against regions',
  'draw.region.removed': 'Region removed',
  'draw.regions.cleared': 'All regions removed',

  // Edit mode
  'edit.mode': 'Edit Mode',
  'edit.editing': 'Editing',
  'edit.vertices': 'vertices',
  'edit.drag': 'Drag to move',
  'edit.dblclick': 'Double-click to remove',
  'edit.midpoint': 'Click midpoint to add',
  'edit.vertex.added': 'Vertex added',
  'edit.vertex.removed': 'Vertex removed',
  'edit.min.vertices': 'Cannot remove: minimum 3 vertices',
  'edit.clipped': 'Region clipped to valid area',
  'edit.done': 'Editing complete',

  // Annotations
  'ann.empty': 'No annotations.',
  'ann.removeall': '🗑️ Remove All',

  // Import
  'import.hint': 'Load custom GeoJSON borders.',

  // Export
  'export.format': 'Format',
  'export.png': 'PNG Image',
  'export.pdf': 'PDF Document',
  'export.svg': 'SVG Vector',
  'export.width': 'Width',
  'export.height': 'Height',
  'export.page': 'Page Size',
  'export.custom.mm': 'Custom (mm)',
  'export.orientation': 'Orientation',
  'export.landscape': 'Landscape',
  'export.portrait': 'Portrait',
  'export.dpi': 'DPI',
  'export.view.info': '📐 <b>Exports visible area.</b> Pan and zoom to frame your map.',
  'export.world': '🌍 World',
  'export.fit': '📐 Fit',
  'export.button': '💾 Export Current View',
  'export.modal.title': '⏳ Exporting',
  'export.preparing': 'Preparing export...',
  'export.rendering.tiles': 'Rendering map tiles...',
  'export.rendering.poly': 'Rendering borders...',
  'export.generating': 'Generating file...',
  'export.done': 'Done!',

  // Banners
  'banner.text': '✏️ Click on map to place text',
  'banner.flag.select': '🏴 Select a flag first',
  'banner.flag.place': '🏴 Click to place {name}',
  'banner.custom.place': '📁 Click to place {name}',
  'banner.draw': '🖊️ Click to start drawing, or select a region to edit',
  'banner.cancel': '✕',

  // Status messages
  'status.ready': 'Ready',
  'status.loading': 'Loading {year}...',
  'status.loaded': '{year}: {count} territories ✓',
  'status.cached': '{year}: {count} territories (cached) ✓',
  'status.error': 'Error loading {year}: {msg}',
  'status.nation.selected': '{count} nation selected',
  'status.nations.selected': '{count} nations selected',
  'status.all.selected': 'All {count} nations selected',
  'status.inverted': 'Selection inverted ({count} selected)',
  'status.deselected': 'Selection cleared',
  'status.select.nation.first': 'Select nations first',
  'status.color.applied': 'Color {color} applied to {count} nation(s)',
  'status.colors.reset': 'All colors reset',
  'status.text.placed': 'Text "{text}" placed',
  'status.flag.select.first': 'Select a flag first',
  'status.flag.placed': '{name} placed',
  'status.custom.added': 'Custom flag "{name}" added',
  'status.custom.removed': 'Custom flag removed',
  'status.format.unsupported': 'Unsupported file format',
  'status.ann.removed': 'Annotation removed',
  'status.ann.cleared': 'All annotations removed',
  'status.imported': '{count} features imported',

  // Loading
  'loading.text': 'Loading...',

  // Countries (for flags)
  'country.us': 'United States',
  'country.gb': 'United Kingdom',
  'country.fr': 'France',
  'country.de': 'Germany',
  'country.it': 'Italy',
  'country.jp': 'Japan',
  'country.ru': 'Russia',
  'country.cn': 'China',
  'country.ca': 'Canada',
  'country.au': 'Australia',
  'country.br': 'Brazil',
  'country.in': 'India',
  'country.es': 'Spain',
  'country.pt': 'Portugal',
  'country.nl': 'Netherlands',
  'country.be': 'Belgium',
  'country.pl': 'Poland',
  'country.tr': 'Turkey',
  'country.mx': 'Mexico',
  'country.ar': 'Argentina',
  'country.se': 'Sweden',
  'country.no': 'Norway',
  'country.fi': 'Finland',
  'country.dk': 'Denmark',
  'country.gr': 'Greece',
  'country.at': 'Austria',
  'country.hu': 'Hungary',
  'country.ro': 'Romania',
  'country.bg': 'Bulgaria',
  'country.rs': 'Serbia',
  'country.hr': 'Croatia',
  'country.ch': 'Switzerland',
  'country.ie': 'Ireland',
  'country.za': 'South Africa',
  'country.eg': 'Egypt',
  'country.sa': 'Saudi Arabia',
  'country.ir': 'Iran',
  'country.iq': 'Iraq',
  'country.th': 'Thailand',
  'country.kr': 'South Korea',
  'country.nz': 'New Zealand',
  'country.ua': 'Ukraine',
  'country.cu': 'Cuba',
  'country.et': 'Ethiopia',
  'country.ng': 'Nigeria',
  'country.pk': 'Pakistan',
  'country.af': 'Afghanistan',
  'country.cl': 'Chile',
  'country.co': 'Colombia',
  'country.pe': 'Peru',
  'country.ve': 'Venezuela',
  'country.dz': 'Algeria',
  'country.ma': 'Morocco',
  'country.ly': 'Libya',
  'country.sd': 'Sudan',
  'country.tn': 'Tunisia',
  'country.sy': 'Syria',
  'country.jo': 'Jordan',
  'country.lb': 'Lebanon',
  'country.il': 'Israel',
  'country.mm': 'Myanmar',
  'country.vn': 'Vietnam',
  'country.ph': 'Philippines',
  'country.id': 'Indonesia',
  'country.my': 'Malaysia',
  'country.bd': 'Bangladesh',
  'country.lk': 'Sri Lanka',
  'country.ke': 'Kenya'
});