// lang-de.js — German translations
registerLanguage('de', {
  // Header
  'header.title': 'Historischer <b>Brettspiel</b> Kartenersteller',

  // Year formatting
  'year.bc': 'v. Chr.',
  'year.ad': 'n. Chr.',

  // Eras
  'era.prehistory': 'Vorgeschichte',
  'era.antiquity': 'Antike',
  'era.firstmill': 'Erstes Jahrtausend',
  'era.medieval': 'Mittelalter',
  'era.earlymodern': 'Frühe Neuzeit',
  'era.nineteenth': '19. Jahrhundert',
  'era.twentieth': '20. Jahrhundert',
  'era.twentyfirst': '21. Jahrhundert',

  // Panels
  'panel.year': '📅 Historisches Jahr',
  'panel.style': '🎨 Kartenstil & Grenzen',
  'panel.colors': '🏳️ Nationenfarben',
  'panel.tools': '🛠️ Werkzeuge',
  'panel.annotations': '📋 Anmerkungen',
  'panel.import': '📂 GeoJSON Importieren',
  'panel.export': '💾 Exportieren',

  // Basemaps
  'basemap.label': 'Basiskarte',
  'basemap.physical': 'Physisch',
  'basemap.relief': 'Schummerung',
  'basemap.natgeo': 'National Geographic',
  'basemap.topo': 'Topographisch',
  'basemap.satellite': 'Satellit',
  'basemap.dark': 'Dunkel',
  'basemap.watercolor': 'Aquarell',
  'basemap.none': 'Keine',

  // Border styles
  'border.style.label': 'Grenzstil',
  'border.solid': 'Durchgehend',
  'border.dashed': 'Gestrichelt',
  'border.dotted': 'Gepunktet',
  'border.dashdot': 'Strich-Punkt',
  'border.longdash': 'Lange Striche',
  'border.double': 'Doppelt',
  'border.sketch': 'Skizze',
  'border.railroad': 'Eisenbahn',
  'border.desc.solid': 'Saubere durchgehende Linie',
  'border.desc.dashed': 'Klassisch gestrichelt',
  'border.desc.dotted': 'Punktmuster',
  'border.desc.dashdot': 'Strich-Punkt-Muster',
  'border.desc.longdash': 'Lange Striche',
  'border.desc.double': 'Doppelte Linie',
  'border.desc.sketch': 'Handgezeichneter Stil',
  'border.desc.railroad': 'Eisenbahnstil',
  'border.width': 'Grenzbreite',
  'border.px': 'px',
  'border.color': 'Grenzfarbe',
  'fill.opacity': 'Fülldeckkraft',

  // Colors panel
  'colors.selected': 'Ausgewählte Nationen',
  'colors.hint': 'Klick = Auswahl · Strg+Klick = Mehrfach · Umsch+Klick = Bereich',
  'colors.empty': 'Klicken Sie auf Nationen in der Karte',
  'colors.all': '✅ Alle',
  'colors.invert': '🔄 Umkehren',
  'colors.none': '✖ Keine',
  'colors.apply.label': 'Farbe anwenden:',
  'colors.custom.label': 'Benutzerdefiniert:',
  'colors.apply': 'Anwenden',
  'colors.reset': '↺ Zurücksetzen',

  // Tools
  'tool.navigate': '🖱️ Navigieren',
  'tool.text': '✏️ Text',
  'tool.flag': '🏴 Flagge',
  'tool.draw': '🖊️ Zeichnen',

  // Text tool
  'text.label': 'Text',
  'text.placeholder': 'Text eingeben...',
  'text.size': 'Größe',
  'text.color': 'Farbe',
  'text.bold': 'Fett',
  'text.outline': 'Umriss',
  'text.rotation': 'Drehung',

  // Flag tool
  'flag.shape': 'Flaggenform',
  'flag.circle': '🔵 Rund',
  'flag.rect': '🟦 Rechteckig',
  'flag.search': 'Suchen',
  'flag.search.placeholder': 'Land suchen...',
  'flag.size': 'Größe',
  'flag.upload.title': 'Eigene Flagge hochladen',
  'flag.upload.desc': 'PNG, SVG, JPG',
  'flag.name.placeholder': 'Flaggenname...',
  'flag.add': '➕ Hinzufügen',
  'flag.builtin': 'Integrierte Flaggen',
  'flag.custom.section': 'Eigene Flaggen',
  'flag.select.hint': '👆 Auswählen, dann auf Karte klicken',
  'flag.selected': 'Ausgewählt: {name}',

  // Draw tool
  'draw.world.mode': 'Weltmodus',
  'draw.world.existing': '🌍 Bestehend',
  'draw.world.empty': '📄 Leer',
  'draw.border.type': 'Grenztyp',
  'draw.type.land': '🏔️ Land',
  'draw.type.sea': '🌊 See',
  'draw.region.name': 'Regionsname',
  'draw.region.placeholder': 'Neue Region',
  'draw.region.color': 'Regionsfarbe',
  'draw.start': '✏️ Zeichnung starten',
  'draw.undo': '↩️ Rückgängig',
  'draw.cancel': '✕ Abbrechen',
  'draw.finish': '✓ Fertig',
  'draw.info.land.desc': 'An Küste beschnitten, bleibt nur auf Land.',
  'draw.info.sea.desc': 'An Küste beschnitten, bleibt nur auf See.',
  'draw.info.overlap.desc': 'Automatischer Beschnitt gegen bestehende Regionen.',
  'draw.regions.title': 'Eigene Regionen',
  'draw.regions.empty': 'Keine Regionen erstellt.',
  'draw.regions.clear': '🗑️ Alle Entfernen',

  // Draw status messages
  'draw.loading.coastline': 'Küstenlinien laden...',
  'draw.mode.empty': 'Leerer Weltmodus — zeichnen Sie Ihre Grenzen',
  'draw.mode.existing': 'Bestehende Grenzen — historische Grenzen geladen',
  'draw.mode.land.hint': 'Landgrenze: wird an Küste beschnitten',
  'draw.mode.sea.hint': 'Seegrenze: kann Land nicht überqueren',
  'draw.started': 'Klicken für Punkte, Doppelklick oder erster Punkt zum Beenden',
  'draw.points': 'Punkte: {count}',
  'draw.point.removed': 'Punkt entfernt',
  'draw.cancelled': 'Zeichnung abgebrochen',
  'draw.need.3.points': 'Mindestens 3 Punkte erforderlich',
  'draw.fully.outside': 'Region komplett außerhalb des gültigen Bereichs (Land/See)',
  'draw.snapped.region': 'An Region eingerastet',
  'draw.snapped.coast.land': 'An Küste eingerastet (Landmodus)',
  'draw.snapped.coast.sea': 'An Küste eingerastet (Seemodus)',
  'draw.cannot.cross.land': '⛔ Seegrenze kann Land nicht überqueren!',
  'draw.region.created': '"{name}" erstellt ({count} Punkte)',
  'draw.clipped.to.land': '· auf Land beschnitten',
  'draw.clipped.to.sea': '· auf See beschnitten',
  'draw.clipped.regions': '· gegen Regionen beschnitten',
  'draw.region.removed': 'Region entfernt',
  'draw.regions.cleared': 'Alle Regionen entfernt',

  // Edit mode
  'edit.mode': 'Bearbeitungsmodus',
  'edit.editing': 'Bearbeitung',
  'edit.vertices': 'Eckpunkte',
  'edit.drag': 'Ziehen zum Verschieben',
  'edit.dblclick': 'Doppelklick zum Entfernen',
  'edit.midpoint': 'Klick auf Mittelpunkt zum Hinzufügen',
  'edit.vertex.added': 'Eckpunkt hinzugefügt',
  'edit.vertex.removed': 'Eckpunkt entfernt',
  'edit.min.vertices': 'Kann nicht entfernen: Minimum 3 Eckpunkte',
  'edit.clipped': 'Region in gültigen Bereich beschnitten',
  'edit.done': 'Bearbeitung abgeschlossen',

  // Annotations
  'ann.empty': 'Keine Anmerkungen.',
  'ann.removeall': '🗑️ Alle Entfernen',

  // Import
  'import.hint': 'Eigene GeoJSON-Grenzen laden.',

  // Export
  'export.format': 'Format',
  'export.png': 'PNG-Bild',
  'export.pdf': 'PDF-Dokument',
  'export.svg': 'SVG-Vektor',
  'export.width': 'Breite',
  'export.height': 'Höhe',
  'export.page': 'Seitengröße',
  'export.custom.mm': 'Benutzerdefiniert (mm)',
  'export.orientation': 'Ausrichtung',
  'export.landscape': 'Querformat',
  'export.portrait': 'Hochformat',
  'export.dpi': 'DPI',
  'export.view.info': '📐 <b>Exportiert den sichtbaren Bereich.</b> Verschieben und zoomen Sie.',
  'export.world': '🌍 Welt',
  'export.fit': '📐 Anpassen',
  'export.button': '💾 Aktuelle Ansicht Exportieren',
  'export.modal.title': '⏳ Exportieren',
  'export.preparing': 'Export vorbereiten...',
  'export.rendering.tiles': 'Kacheln rendern...',
  'export.rendering.poly': 'Grenzen rendern...',
  'export.generating': 'Datei generieren...',
  'export.done': 'Fertig!',

  // Banners
  'banner.text': '✏️ Klicken Sie auf die Karte um Text zu platzieren',
  'banner.flag.select': '🏴 Wählen Sie zuerst eine Flagge',
  'banner.flag.place': '🏴 Klicken um {name} zu platzieren',
  'banner.custom.place': '📁 Klicken um {name} zu platzieren',
  'banner.draw': '🖊️ Klicken zum Zeichnen, oder Region zum Bearbeiten wählen',
  'banner.cancel': '✕',

  // Status messages
  'status.ready': 'Bereit',
  'status.loading': 'Lade {year}...',
  'status.loaded': '{year}: {count} Gebiete ✓',
  'status.cached': '{year}: {count} Gebiete (Cache) ✓',
  'status.error': 'Fehler beim Laden {year}: {msg}',
  'status.nation.selected': '{count} Nation ausgewählt',
  'status.nations.selected': '{count} Nationen ausgewählt',
  'status.all.selected': 'Alle {count} Nationen ausgewählt',
  'status.inverted': 'Auswahl umgekehrt ({count} ausgewählt)',
  'status.deselected': 'Auswahl aufgehoben',
  'status.select.nation.first': 'Wählen Sie zuerst Nationen',
  'status.color.applied': 'Farbe {color} auf {count} Nation(en) angewendet',
  'status.colors.reset': 'Alle Farben zurückgesetzt',
  'status.text.placed': 'Text "{text}" platziert',
  'status.flag.select.first': 'Wählen Sie zuerst eine Flagge',
  'status.flag.placed': '{name} platziert',
  'status.custom.added': 'Eigene Flagge "{name}" hinzugefügt',
  'status.custom.removed': 'Eigene Flagge entfernt',
  'status.format.unsupported': 'Dateiformat nicht unterstützt',
  'status.ann.removed': 'Anmerkung entfernt',
  'status.ann.cleared': 'Alle Anmerkungen entfernt',
  'status.imported': '{count} Elemente importiert',

  // Loading
  'loading.text': 'Laden...',

  // Countries
  'country.us': 'Vereinigte Staaten',
  'country.gb': 'Vereinigtes Königreich',
  'country.fr': 'Frankreich',
  'country.de': 'Deutschland',
  'country.it': 'Italien',
  'country.jp': 'Japan',
  'country.ru': 'Russland',
  'country.cn': 'China',
  'country.ca': 'Kanada',
  'country.au': 'Australien',
  'country.br': 'Brasilien',
  'country.in': 'Indien',
  'country.es': 'Spanien',
  'country.pt': 'Portugal',
  'country.nl': 'Niederlande',
  'country.be': 'Belgien',
  'country.pl': 'Polen',
  'country.tr': 'Türkei',
  'country.mx': 'Mexiko',
  'country.ar': 'Argentinien',
  'country.se': 'Schweden',
  'country.no': 'Norwegen',
  'country.fi': 'Finnland',
  'country.dk': 'Dänemark',
  'country.gr': 'Griechenland',
  'country.at': 'Österreich',
  'country.hu': 'Ungarn',
  'country.ro': 'Rumänien',
  'country.bg': 'Bulgarien',
  'country.rs': 'Serbien',
  'country.hr': 'Kroatien',
  'country.ch': 'Schweiz',
  'country.ie': 'Irland',
  'country.za': 'Südafrika',
  'country.eg': 'Ägypten',
  'country.sa': 'Saudi-Arabien',
  'country.ir': 'Iran',
  'country.iq': 'Irak',
  'country.th': 'Thailand',
  'country.kr': 'Südkorea',
  'country.nz': 'Neuseeland',
  'country.ua': 'Ukraine',
  'country.cu': 'Kuba',
  'country.et': 'Äthiopien',
  'country.ng': 'Nigeria',
  'country.pk': 'Pakistan',
  'country.af': 'Afghanistan',
  'country.cl': 'Chile',
  'country.co': 'Kolumbien',
  'country.pe': 'Peru',
  'country.ve': 'Venezuela',
  'country.dz': 'Algerien',
  'country.ma': 'Marokko',
  'country.ly': 'Libyen',
  'country.sd': 'Sudan',
  'country.tn': 'Tunesien',
  'country.sy': 'Syrien',
  'country.jo': 'Jordanien',
  'country.lb': 'Libanon',
  'country.il': 'Israel',
  'country.mm': 'Myanmar',
  'country.vn': 'Vietnam',
  'country.ph': 'Philippinen',
  'country.id': 'Indonesien',
  'country.my': 'Malaysia',
  'country.bd': 'Bangladesch',
  'country.lk': 'Sri Lanka',
  'country.ke': 'Kenia'
});